import Foundation

struct AlphabetHints {
    static let data: [String: String] = [
        // MARK: - Geografie
        "Bis zu welchem Buchstaben kommst du bei Ländern?": """
        Afghanistan, Ägypten, Albanien, Algerien, Andorra, Angola, Argentinien, Armenien, Australien,
        Bahamas, Bahrain, Bangladesch, Barbados, Belgien, Belize, Benin, Bhutan, Bolivien, Bosnien und Herzegowina, Botsuana, Brasilien, Brunei, Bulgarien, Burkina Faso,
        Chile, China, Costa Rica, Côte d'Ivoire,
        Dänemark, Deutschland, Dominica, Dominikanische Republik, Dschibuti,
        Ecuador, El Salvador, Eritrea, Estland, Eswatini,
        Fidschi, Finnland, Frankreich,
        Gabun, Gambia, Georgien, Ghana, Grenada, Griechenland, Guatemala, Guinea, Guinea-Bissau, Guyana,
        Haiti, Honduras,
        Indien, Indonesien, Irak, Iran, Irland, Island, Israel, Italien,
        Jamaika, Japan, Jemen, Jordanien,
        Kambodscha, Kamerun, Kanada, Kap Verde, Kasachstan, Katar, Kenia, Kirgisistan, Kiribati, Kolumbien, Komoren, Kongo, Kroatien, Kuba, Kuwait,
        Laos, Lesotho, Lettland, Libanon, Liberia, Libyen, Liechtenstein, Litauen, Luxemburg,
        Madagaskar, Malawi, Malaysia, Malediven, Mali, Malta, Marokko, Marshallinseln, Mauretanien, Mauritius, Mexiko, Mikronesien, Moldau, Monaco, Mongolei, Montenegro, Mosambik, Myanmar,
        Namibia, Nauru, Nepal, Neuseeland, Nicaragua, Niederlande, Niger, Nigeria, Nordkorea, Nordmazedonien, Norwegen,
        Oman, Österreich, Osttimor,
        Pakistan, Palau, Panama, Papua-Neuguinea, Paraguay, Peru, Philippinen, Polen, Portugal,
        Ruanda, Rumänien, Russland,
        Salomonen, Sambia, Samoa, San Marino, Saudi-Arabien, Schweden, Schweiz, Senegal, Serbien, Seychellen, Sierra Leone, Simbabwe, Singapur, Slowakei, Slowenien, Somalia, Spanien, Sri Lanka, St. Kitts und Nevis, St. Lucia, Südafrika, Sudan, Südkorea, Suriname, Syrien,
        Tadschikistan, Tansania, Thailand, Togo, Tonga, Trinidad und Tobago, Tschad, Tschechien, Tunesien, Türkei, Turkmenistan, Tuvalu,
        Uganda, Ukraine, Ungarn, Uruguay, USA, Usbekistan,
        Vanuatu, Vatikanstadt, Venezuela, Vereinigte Arabische Emirate, Vereinigtes Königreich, Vietnam,
        Weißrussland,
        Zentralafrikanische Republik, Zypern
        """,
        
        "Bis zu welchem Buchstaben kommst du bei europäischen Städten?": """
        Amsterdam, Athen, Antwerpen, Aarhus, Aberdeen, Alicante,
        Barcelona, Berlin, Brüssel, Budapest, Belgrad, Bern, Bratislava, Bukarest, Basel, Birmingham, Bologna, Bordeaux, Bremen, Bristol, Brügge,
        Cannes, Catania, Charleroi, Chisinau, Cork, Cambridge, Cardiff,
        Dublin, Dortmund, Dresden, Düsseldorf, Danzig, Debrecen, Den Haag, Dijon,
        Edinburgh, Essen, Eindhoven, Florenz, Frankfurt, Genf, Glasgow, Göteborg, Graz, Granada, Gent,
        Hamburg, Helsinki, Hannover, Heidelberg, Istanbul, Innsbruck, Kopenhagen, Köln, Krakau, Kiew, Lissabon, London, Lyon, Liverpool, Leipzig, Lausanne, Lille, Linz, Ljubljana, Luxemburg,
        Madrid, Mailand, München, Manchester, Marseille, Malmö, Minsk, Monaco, Moskau, Neapel, Nizza, Nantes, Nürnberg, Oslo, Ostrava, Oxford,
        Paris, Prag, Porto, Palermo, Pisa, Podgorica, Posen, Potsdam, Reykjavik, Riga, Rom, Rotterdam, Salzburg, Sarajevo, Sevilla, Sofia, Stockholm, Stuttgart, Skopje, Split, Straßburg,
        Tallinn, Tirana, Turin, Thessaloniki, Toulouse, Trondheim, Uppsala, Utrecht, Valencia, Venedig, Verona, Vilnius, Warschau, Wien, Zagreb, Zürich, Zaragossa
        """,
        
        "Bis zu welchem Buchstaben kommst du bei deutschen Städten?": """
        Aachen, Augsburg, Aschaffenburg, Amberg, Aalen, Ahlen, Altenburg, Arnsberg,
        Berlin, Bonn, Bielefeld, Bochum, Bremen, Braunschweig, Bottrop, Bamberg, Bayreuth,
        Chemnitz, Cottbus, Coburg, Celle, Castrop-Rauxel, Cuxhaven, Crailsheim,
        Dortmund, Dresden, Düsseldorf, Duisburg, Darmstadt, Dessau, Düren, Detmold,
        Essen, Erfurt, Erlangen, Emden, Euskirchen, Eisenach, Elmshorn, Erding,
        Frankfurt, Freiburg, Fürth, Flensburg, Fulda, Friedrichshafen, Freising, Frankenthal,
        Gelsenkirchen, Gera, Göttingen, Gütersloh, Gießen, Gladbeck, Greifswald, Goslar,
        Hamburg, Hannover, Heidelberg, Heilbronn, Hagen, Halle, Hamm, Herne, Hanau,
        Ingolstadt, Iserlohn, Ibbenbüren, Idar-Oberstein, Ilmenau, Ingelheim, Itzehoe,
        Jena, Jülich,
        Köln, Karlsruhe, Kiel, Krefeld, Kassel, Koblenz, Kaiserslautern, Konstanz, Kempten,
        Leipzig, Lübeck, Leverkusen, Ludwigshafen, Lüneburg, Landshut, Ludwigsburg, Lippstadt,
        München, Mannheim, Münster, Magdeburg, Mainz, Mönchengladbach, Mülheim, Moers, Marburg,
        Nürnberg, Neuss, Norderstedt, Neu-Ulm, Nordhausen, Neustadt, Neubrandenburg,
        Oberhausen, Osnabrück, Oldenburg, Offenbach, Oranienburg, Offenburg, Olpe,
        Potsdam, Paderborn, Pforzheim, Plauen, Passau, Pirna, Peine, Pirmasens,
        Quedlinburg, Quickborn,
        Regensburg, Rostock, Recklinghausen, Remscheid, Reutlingen, Rosenheim, Ravensburg, Ratingen,
        Stuttgart, Saarbrücken, Solingen, Siegen, Salzgitter, Schwerin, Speyer, Schweinfurt,
        Trier, Tübingen, Troisdorf, Tuttlingen, Torgau,
        Ulm, Unna, Uelzen,
        Villingen-Schwenningen, Velbert, Viersen, Voerde, Verden,
        Wiesbaden, Wuppertal, Wolfsburg, Würzburg, Worms, Wilhelmshaven, Weimar, Wesel,
        Xanten,
        Zwickau, Zweibrücken, Zittau, Zeitz
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Flüssen weltweit?": """
        Amazonas, Amur, Arkansas, Aare, Aller, Alster,
        Brahmaputra, Benue, Blau, Bober, Colorado, Columbia, Congo, Check,
        Donau, Dnepr, Don, Delaware, Darling, Ebro, Elbe, Ems, Euphrat, Etsch,
        Ganges, Gelber Fluss, Gambia, Garonne, Havel, Hudson, Humber, Indus, Inn, Isar, Irtysch, Irrawaddy,
        Jangtsekiang, Jordan, Yukon, Kongo, Kasai, Lena, Loire, Limpopo, Lahn, Lech,
        Mekong, Mississippi, Missouri, Main, Mosel, Murray, Maas, Mackenzie, Moldau,
        Nil, Niger, Neckar, Nelson, Neiße, Oder, Ob, Orinoco, Orange, Ohio,
        Paraná, Paraguay, Po, Peene, Pregel, Rhein, Rhone, Rio Grande, Ruhr, Ruwer,
        Seine, Spree, Saar, Sambesi, Sankt-Lorenz-Strom, Senne, Schelde,
        Themse, Tiber, Tigris, Tagus, Trave, Ural, Ubangi, Volga, Vistula, Weser, Wolga, Weichsel, Werra,
        Xi Jiang, Xingu, Yukon, Yarra, Zambezi
        """,
        
        // MARK: - Alltag & Marken
        "Bis zu welchem Buchstaben kommst du bei Automarken?": """
        Audi, Aston Martin, Alfa Romeo, Alpine, Acura, Abarth,
        BMW, Bentley, Bugatti, Buick, BYD, Borgward,
        Chevrolet, Citroën, Cadillac, Chrysler, Cupra, Corvette, Caterham,
        Dacia, Dodge, DS Automobiles, Daihatsu, De Tomaso,
        E.Go,
        Ferrari, Ford, Fiat, Fisker, Fuso,
        GMC, Genesis, Geely, Gumpert, Great Wall,
        Honda, Hyundai, Hummer, Holden, Hennessey,
        Infiniti, Isuzu, Iveco, Ineos,
        Jaguar, Jeep, JAC,
        Kia, Koenigsegg, KTM, Karma,
        Lamborghini, Land Rover, Lexus, Lotus, Lancia, Lincoln, Lada, Lucid,
        Mercedes-Benz, Maserati, Mazda, Mini, McLaren, Mitsubishi, Maybach, MG, Morgan, MAN,
        Nissan, Nio,
        Opel, Ora,
        Porsche, Peugeot, Polestar, Pagani, Pontiac, Plymouth, Piaggio,
        Qoros,
        Renault, Rolls-Royce, Rimac, Ram, Rover, Ruf,
        Seat, Skoda, Subaru, Suzuki, Smart, Saab, Shelby, SsangYong, Scania,
        Tesla, Toyota, Tata, Triumph, Trabant, TVR,
        Unimog,
        Volkswagen, Volvo, Vauxhall, VinFast,
        Wartburg, Wiesmann, Wey,
        Xpeng,
        Yamaha,
        Zenvo
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Kleidungsmarken?": """
        Adidas, Armani, Asos, Abercrombie & Fitch, Alexander McQueen, Alpha Industries,
        Balenciaga, Boss, Burberry, Bershka, Birkenstock, Bench, Bogner,
        Calvin Klein, Chanel, Converse, Carhartt, Champion, Columbia, C&A, Canada Goose,
        Dior, Dolce & Gabbana, Diesel, Dr. Martens, Dickies, Desigual,
        Esprit, Ellesse, Escada, Etnies, Fendi, Fila, Fossil, Fred Perry, Fruit of the Loom,
        Gucci, Gap, G-Star, Givenchy, Guess, Gant, H&M, Hollister, Hermes, Hugo Boss, Helly Hansen,
        Jack & Jones, Jack Wolfskin, Jordan, Jil Sander, Kappa, Karl Kani, Kenzo, Calvin Klein,
        Lacoste, Levi's, Louis Vuitton, Lee, Lululemon, Mango, Michael Kors, Moncler, Moschino, Marc O'Polo,
        Nike, New Balance, North Face, Napapijri, New Era, Only, Off-White, Oakley, O'Neill,
        Prada, Puma, Patagonia, Pepe Jeans, Pull & Bear, Polo Ralph Lauren, Quiksilver,
        Ralph Lauren, Reebok, Ray-Ban, Roxy, Replay, Skechers, Superdry, Stüssy, Stone Island, s.Oliver, Supreme,
        Timberland, Tommy Hilfiger, Tom Tailor, The North Face, Topshop, Under Armour, Uniqlo, Urban Outfitters, UGG,
        Vans, Versace, Valentino, Vero Moda, Volcom, Woolrich, Wrangler, Wellensteyn, Zara
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Dingen, die man im Supermarkt kauft?": """
        Apfel, Ananas, Alufolie, Aufschnitt, Avocado, Backpulver, Banane, Brot, Butter, Bier, Batterien, Birne, Bohnen,
        Chips, Cola, Creme Fraiche, Cornflakes, Curry, Deo, Duschgel, Dosenmais, Eier, Eis, Erbsen, Essig, Erdbeeren,
        Fisch, Fleisch, Frischkäse, Fruchtsaft, Gurke, Gemüse, Gewürze, Gummibärchen,
        Honig, Handseife, Haferflocken, Hundefutter, Hefe, Ingwer, Joghurt, Kaffee, Käse, Ketchup, Kartoffeln, Kekse, Kerzen, Klopapier, Kaugummi,
        Limonade, Lachs, Milch, Mehl, Marmelade, Müllbeutel, Müsli, Mandarinen, Nudeln, Nüsse, Nutella,
        Obst, Öl, Oliven, Orangen, Pizza, Pasta, Pfeffer, Paprika, Quark, Reis, Rasierschaum, Reiniger,
        Salz, Salat, Shampoo, Schokolade, Senf, Salami, Seife, Serviette, Spaghetti, Speiseöl, Schwamm,
        Tee, Tomaten, Taschentücher, Tiefkühlpizza, Toast, Trauben, Thunfisch,
        Vanillezucker, Vollkornbrot, Wasser, Waschmittel, Wein, Wurst, Windeln, Wattepads, Zahnpasta, Zucker, Zitrone, Zwiebel, Zucchini
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Obst- oder Gemüsesorten?": """
        Ananas, Apfel, Aprikose, Aubergine, Avocado, Banane, Birne, Blumenkohl, Bohne, Brokkoli, Brombeere,
        Chili, Chicorée, Chinakohl, Clementine, Dattel, Durian, Erdbeere, Erbse, Endivie, Feige, Feldsalat, Fenchel,
        Granatapfel, Grapefruit, Grünkohl, Gurke, Heidelbeere, Himbeere, Holunder, Honigmelone, Ingwer,
        Johannisbeere, Kartoffel, Karotte, Kirsche, Kiwi, Knoblauch, Kohlrabi, Kokosnuss, Kürbis,
        Lauch, Limette, Litschi, Mais, Mandarine, Mango, Mangold, Maracuja, Melone, Mirabelle, Möhre,
        Nektarine, Olive, Orange, Papaya, Paprika, Pastinake, Pfirsich, Pflaume, Pilz, Porree, Preiselbeere,
        Quitte, Radieschen, Rhabarber, Rosenkohl, Rote Bete, Rucola, Salat, Sauerkirsche, Schnittlauch, Schwarzwurzel, Sellerie, Spargel, Spinat, Stachelbeere, Süßkartoffel,
        Tomate, Traube, Wassermelone, Weintraube, Weißkohl, Wirsing, Zitrone, Zucchini, Zwetschge, Zwiebel
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Süßigkeiten?": """
        After Eight, Amicelli, Apfelringe, Balisto, Bärenmarke, Bounty, Brause, Bonbon, Bueno,
        Celebrations, Choco Crossies, Chips, Chupa Chups, Cola-Fläschchen, Daim, Dickmanns, Dominosteine, Donut, Duplo, Dauerlutscher,
        Eiskonfekt, Eis, Erdnussflips, Esspapier, Ferrero Rocher, Fruchtgummi, Giotto, Gummibärchen, Geleebananen,
        Hanuta, Haribo, Hershey's, Hubba Bubba, Halloren Kugeln, Ingwerstäbchen,
        Jelly Beans, Jogurette, Kinder Riegel, Kaugummi, Keks, KitKat, Knoppers, Lakritz, Lebkuchen, Lindt, Lion, Lutscher, Liebesperlen,
        M&M's, Maoam, Mars, Marzipan, Mentos, Milchschnitte, Milka, Milky Way, Mon Cheri, Mozartkugeln, Marshmallow, Muffin,
        Nimm2, Nippon, Nougat, Nutella, Oreo, Praline, Prinzenrolle, Popcorn, Puffreis,
        Raffaello, Reese's, Ritter Sport, Rolo, Russisch Brot,
        Schokolade, Schokobon, Schokokuss, Skittles, Smarties, Snickers, Spekulatius, Storck Riesen,
        Toblerone, Toffifee, Traubenzucker, Twix, Tic Tac, Überraschungsei,
        Waffel, Weingummi, Werther's Original, Wunderbar, Yogurette, Zuckerstange, Zuckerwatte, Zimtstern
        """,
        
        // MARK: - Natur & Tiere
        "Bis zu welchem Buchstaben kommst du bei Tieren?": """
        Affe, Ameise, Adler, Alligator, Alpaka, Amsel, Antilope, Axolotl,
        Bär, Biene, Biber, Büffel, Braunbär, Blaumeise, Bussard, Bonobo,
        Chamäleon, Chinchilla, Clownfisch, Cobra, Capybara,
        Dachs, Delfin, Dackel, Dromedar, Dohle, Dorsch,
        Esel, Elefant, Elch, Eichhörnchen, Eisbär, Ente, Eule, Erdmännchen, Echse,
        Fuchs, Fledermaus, Fisch, Flamingo, Frosch, Falken, Frettchen, Flusspferd,
        Giraffe, Gepard, Gans, Gorilla, Gazelle, Geier, Gürteltier, Goldfisch,
        Hund, Hase, Hamster, Hirsch, Huhn, Hai, Hummel, Hyäne, Habicht,
        Igel, Iltis, Impala, Leguan,
        Jaguar,
        Katze, Kamel, Känguru, Koala, Krokodil, Kröte, Karpfen, Kaninchen, Krake,
        Löwe, Luchs, Lama, Leopard, Lemur, Libelle, Lachs,
        Maus, Maulwurf, Meerschweinchen, Murmeltier, Marder, Möwe, Marienkäfer, Qualle,
        Nashorn, Nilpferd, Nasenbär, Nerz, Nutria,
        Ochse, Otter, Orang-Utan, Oktopus,
        Pferd, Pinguin, Panda, Papagei, Pfau, Puma, Panther, Pelikan,
        Qualle, Quokka,
        Ratte, Reh, Rentier, Rind, Rabe, Rotkehlchen, Raupe,
        Schwein, Schaf, Schlange, Schildkröte, Seehund, Spinne, Schwan, Schnecke, Stier,
        Tiger, Taube, Truthahn, Tapir, Tarantel, Thunfisch,
        Uhu, Unke,
        Vogel, Vogelspinne, Vielfraß,
        Wolf, Wal, Waschbär, Wildschwein, Wiesel, Wurm, Waran, Wels,
        Yak,
        Zebra, Ziege, Zitteraal, Zaunkönig, Zebu
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Hunderassen?": """
        Australian Shepherd, Akita, Affenpinscher, Afghanischer Windhund, Airedale Terrier,
        Beagle, Boxer, Bernhardiner, Border Collie, Bulldogge, Bullterrier, Berner Sennenhund, Bolonka,
        Chihuahua, Chow Chow, Cocker Spaniel, Collie, Corgi, Cane Corso,
        Dackel, Dalmatiner, Dobermann, Deutsche Dogge, Deutsch Drahthaar,
        Englische Bulldogge, Eurasier, Foxterrier, Französische Bulldogge,
        Golden Retriever, Greyhound, Großer Schweizer Sennenhund,
        Havaneser, Husky, Hovawart, Irischer Wolfshund, Jack Russell Terrier,
        Labrador, Leonberger, Lhasa Apso, Malteser, Mops, Mastiff, Münsterländer,
        Neufundländer, Otterhund, Pudel, Pinscher, Pekinese, Pitbull, Pointer,
        Rottweiler, Rhodesian Ridgeback, Riesenschnauzer,
        Schäferhund, Schnauzer, Shiba Inu, Spitz, Setter, Sennenhund, Shar-Pei, Shih Tzu,
        Teckel, Terrier, Vizsla, Weimaraner, West Highland Terrier, Windhund, Wolfsspitz, Yorkshire Terrier, Zwergpudel, Zwergspitz
        """,
        
        // MARK: - Wissen & Kultur
        "Bis zu welchem Buchstaben kommst du bei Berufen?": """
        Architekt, Arzt, Anwalt, Apotheker, Astronaut, Altenpfleger, Augenoptiker,
        Bäcker, Bankkaufmann, Bauer, Bauarbeiter, Biologe, Buchhalter, Busfahrer, Bestatter, Bibliothekar,
        Chemiker, Chirurg, Clown, Coach, Dachdecker, Detektiv, Designer, Dolmetscher, DJ,
        Elektriker, Erzieher, Ergotherapeut, Eventmanager, Feuerwehrmann, Fischer, Fotograf, Fleischer, Flugbegleiter, Förster, Friseur,
        Gärtner, Glaser, Grafikdesigner, Geologe, Gerüstbauer, Goldschmied,
        Hebamme, Hausmeister, Hotelfachmann, Historiker, Handwerker, Informatiker, Immobilienmakler, Ingenieur, Innenarchitekt,
        Journalist, Justizvollzugsbeamter, Jäger, Juwelier, Kaufmann, Kellner, Koch, Krankenpfleger, Künstler, Klempner, Kapitän, Konditor,
        Lackierer, Lehrer, Logopäde, Landwirt, LKW-Fahrer, Maler, Maurer, Mechaniker, Mediengestalter, Metzger, Model, Musiker,
        Notar, Notfallsanitäter, Optiker, Pilot, Pfarrer, Physiotherapeut, Polizist, Programmierer, Psychologe,
        Qualitätsmanager, Rechtsanwalt, Redakteur, Regisseur, Reporter, Richter,
        Sanitäter, Schauspieler, Schreiner, Sekretär, Soldat, Sozialarbeiter, Steuerberater, Stewardess,
        Taxifahrer, Techniker, Tierarzt, Tischler, Trainer, Unternehmer, Uhrmacher,
        Verkäufer, Versicherungskaufmann, Webdesigner, Winzer, Zahnarzt, Zimmermann, Zoologe
        """,
        
        "Bis zu welchem Buchstaben kommst du bei weiblichen Vornamen?": """
        Anna, Alina, Amelie, Andrea, Anja, Antonia, Astrid, Ava,
        Barbara, Bea, Bella, Bianca, Birgit, Brigitte, Britta,
        Carla, Carmen, Carolin, Celina, Charlotte, Chiara, Christina, Clara, Claudia,
        Daniela, Denise, Diana, Dora, Doris, Dorothea,
        Elena, Elisa, Elisabeth, Ella, Emilia, Emma, Erika, Eva, Evelyn,
        Fabienne, Felicitas, Fiona, Franziska, Frieda,
        Gabi, Gabriele, Gesa, Gina, Gisela, Greta,
        Hanna, Heidi, Helena, Helga, Henriette,
        Ida, Ilse, Ina, Ines, Ingrid, Irene, Isabel, Ivonne,
        Jacqueline, Jana, Janina, Jasmin, Jennifer, Jessica, Johanna, Jule, Julia,
        Karin, Karlotta, Katharina, Katja, Kerstin, Kim, Klara, Kristin,
        Lara, Laura, Lea, Lena, Leonie, Lilly, Lina, Lisa, Lotte, Louisa,
        Maja, Manuela, Mara, Mareike, Maria, Marie, Marina, Marlene, Martha, Melanie, Mia, Michelle, Mila, Miriam, Mona, Monika,
        Nadine, Natalie, Nele, Nicole, Nina, Nora,
        Olivia, Olga,
        Patricia, Paula, Pauline, Petra, Pia,
        Ramona, Rebecca, Regina, Renate, Romy, Ronja, Rosa,
        Sabine, Sabrina, Sandra, Sarah, Saskia, Silvia, Simone, Sina, Sofia, Sophie, Stefanie, Steffi, Svenja,
        Tabea, Tamara, Tanja, Teresa, Theresa, Tina,
        Ulla, Ulrike, Ursula, Ute,
        Valerie, Vanessa, Vera, Verena, Victoria, Viola,
        Waltraud, Wiebke,
        Xenia,
        Yvonne,
        Zoe
        """,
        
        "Bis zu welchem Buchstaben kommst du bei männlichen Vornamen?": """
        Aaron, Adam, Adrian, Alexander, Andreas, Anton, Armin, Arthur, Axel,
        Ben, Benedikt, Benjamin, Bernd, Bernhard, Björn, Boris, Bruno,
        Carl, Christian, Christoph, Clemens, Constantin,
        Daniel, David, Dennis, Dieter, Dirk, Dominik,
        Elias, Emil, Eric, Ernst,
        Fabian, Felix, Finn, Florian, Frank, Franz, Friedrich, Fritz,
        Gabriel, Georg, Gerhard, Gerrit, Günther,
        Hannes, Hans, Harald, Harry, Heiko, Heinrich, Heinz, Helge, Hendrik, Henry, Herbert, Hermann, Holger, Horst,
        Ingo,
        Jakob, Jan, Jannik, Jens, Joachim, Johannes, Jonas, Jonathan, Jörg, Julian, Jürgen, Justin,
        Kai, Karl, Karsten, Kevin, Kilian, Klaus, Konstantin, Kurt,
        Lars, Lasse, Lennard, Leo, Leon, Levin, Liam, Linus, Lorenz, Lothar, Luca, Lucas, Ludwig, Luis, Lukas,
        Maik, Malte, Manfred, Manuel, Marc, Marcel, Marco, Marcus, Mario, Markus, Martin, Marvin, Mathias, Mats, Matteo, Matthias, Max, Maximilian, Michael, Moritz,
        Nils, Noah, Norbert,
        Olaf, Ole, Oliver, Oskar, Otto,
        Patrick, Paul, Peter, Philip, Philipp,
        Rafael, Rainer, Ralf, Ralph, Raphael, René, Richard, Robert, Robin, Roland, Rolf, Roman, Rudolf,
        Samuel, Sascha, Sebastian, Simon, Stefan, Steffen, Stephan, Sven,
        Theo, Thomas, Thorsten, Tim, Timo, Tobias, Tom, Torsten,
        Udo, Ulrich, Uwe,
        Valentin, Vincent, Volker,
        Walter, Werner, Wilhelm, Wolfgang,
        Yannick,
        Ziegler
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Sportarten?": """
        American Football, Angeln, Aerobic, Aikido,
        Badminton, Ballet, Baseball, Basketball, Beachvolleyball, Biathlon, Billard, Bobfahren, Bogenschießen, Bowling, Boxen,
        Cheerleading, Cricket, Curling, Crossfit,
        Dart, Dressurreiten, Diskuswerfen, Eishockey, Eiskunstlauf, Eisschnelllauf, Fechten, Formel 1, Fußball, Faustball,
        Golf, Geräteturnen, Gewichtheben, Gymnastik,
        Handball, Hochsprung, Hürdenlauf, Hockey,
        Inlineskaten, Judo, Joggen, Kanu, Karate, Kartfahren, Kitesurfen, Klettern, Krafttraining, Kung Fu,
        Lacrosse, Leichtathletik, Laufen,
        Marathon, Motocross, Mountainbiken, Motorsport,
        Nordic Walking,
        Orientierungslauf,
        Parkour, Pilates, Polo, Paintball,
        Quidditch,
        Radsport, Reiten, Rennrodeln, Ringen, Rudern, Rugby,
        Schach, Schwimmen, Segeln, Skateboarden, Skifahren, Skispringen, Snowboarden, Softball, Squash, Surfen, Sumo,
        Taekwondo, Tanzen, Tauchen, Tennis, Tischtennis, Trampolin, Triathlon, Turnen,
        Volleyball, Völkerball,
        Wasserball, Wasserski, Weitsprung, Wrestling, Windsurfen, Wandern,
        Yoga,
        Zehnkampf, Zumba
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Körperteilen?": """
        Arm, Auge, Augenbraue, Augenlid, Achsel, Ader, Arsch,
        Bauch, Bauchnabel, Bart, Bein, Becken, Bizeps, Brust, Busen, Backenzahn,
        Darm, Daumen, Dickdarm, Dünndarm,
        Ellenbogen,
        Ferse, Finger, Fingernagel, Fuß, Fußknöchel,
        Gaumen, Gebärmutter, Gehirn, Gesicht, Gesäß, Gelenk, Genick,
        Hals, Hand, Handgelenk, Haut, Herz, Hintern, Hirn, Hoden, Hüfte, Haar, Hacke,
        Iris,
        Jochbein,
        Kiefer, Kinn, Knie, Kniescheibe, Knöchel, Knochen, Kopf, Körper, Kreuz,
        Leber, Leiste, Lippe, Lunge, Lende,
        Magen, Mandel, Mund, Muskel, Milz,
        Nabel, Nacken, Nagel, Nase, Nasenloch, Nerv, Niere,
        Ohr, Oberarm, Oberschenkel,
        Penis, Po, Popo, Pupille,
        Rachen, Rippe, Rücken, Rumpf,
        Schenkel, Schienbein, Schilddrüse, Schulter, Schädel, Speiseröhre, Stirn, Steißbein,
        Taille, Trommelfell, Trizeps,
        Unterarm, Unterschenkel,
        Vene,
        Wade, Wange, Wirbel, Wirbelsäule, Wimper,
        Zahn, Zeh, Zunge, Zäpfchen, Zwerchfell
        """,
        
        // MARK: - Medien
        "Bis zu welchem Buchstaben kommst du bei Disney-Charakteren?": """
        Aladdin, Alice, Anna, Arielle, Aurora, Abu,
        Bambi, Balu, Belle, Baymax, Buzz Lightyear, Biest,
        Cap und Capper, Cinderella, Captain Hook, Chip, Chap, Cruella de Vil, Coco,
        Daisy Duck, Dumbo, Donald Duck, Dorie, Dagobert Duck, Dornröschen,
        Elsa, Eeyore, Erik,
        Fabius, Flynn Rider, Ferkel,
        Genie, Goofy, Gaston, Gustav Gans,
        Hades, Hercules, Hook,
        I-AAH,
        Jasmin, Jafar, Judy Hopps,
        Klopfer, Kaa, Kristoff, Kuzco, Kermit, Kim Possible,
        Lilo, Lumière, Lightning McQueen,
        Maus, Micky Maus, Minnie Maus, Mulan, Merida, Moana, Mushu, Mowgli, Maleficent, Mike Glotzkowski, Meister Eder,
        Nala, Nemo, Nemo,
        Olaf, Onkel Dagobert,
        Peter Pan, Pinocchio, Pluto, Pocahontas, Pumbaa, Piglet,
        Quasimodo,
        Rapunzel, Rafiki, Robin Hood, Remy,
        Scar, Schneewittchen, Simba, Stitch, Susi, Strolch, Sulley, Sebastian,
        Tarzan, Tiana, Tick, Trick, Track, Thaddäus, Tigger, Timon, Tinkerbell,
        Ursula,
        Vaiana, Violetta,
        Winnie Puuh, Wall-E, Woody,
        Zazu
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Harry Potter Charakteren?": """
        Albus Dumbledore, Arthur Weasley, Argus Filch,
        Bellatrix Lestrange, Bill Weasley,
        Cedric Diggory, Cho Chang, Colin Creevey, Crabbe,
        Draco Malfoy, Dobby, Dudley Dursley, Dean Thomas, Dolores Umbridge,
        Fleur Delacour, Fred Weasley,
        George Weasley, Gilderoy Lockhart, Ginny Weasley, Godric Gryffindor, Goyle,
        Harry Potter, Hagrid, Hermine Granger, Hedwig, Horace Slughorn,
        Igor Karkaroff,
        James Potter,
        Kingsley Shacklebolt, Kreacher,
        Lily Potter, Lucius Malfoy, Luna Lovegood, Lavender Brown, Lord Voldemort,
        Minerva McGonagall, Molly Weasley, Maulende Myrte, Mad-Eye Moody,
        Narcissa Malfoy, Neville Longbottom, Nymphadora Tonks, Nagini,
        Oliver Wood,
        Percy Weasley, Peter Pettigrew, Petunia Dursley, Padme Patil, Parvati Patil, Pansy Parkinson,
        Quirrell,
        Remus Lupin, Ron Weasley, Rubeus Hagrid, Rita Kimmkorn, Regulus Black,
        Severus Snape, Sirius Black, Seamus Finnigan, Salazar Slytherin, Sybill Trelawney,
        Tom Riddle, Tonks,
        Vernon Dursley, Voldemort, Viktor Krum,
        Wurmscbwantz,
        Xenophilius Lovegood
        """,
        
        "Bis zu welchem Buchstaben kommst du bei berühmten Prominenten (Nachname)?": """
        Adele, Aniston, Affleck, Ali, Alba,
        Beckham, Bieber, Beyoncé, Pitt, Bullock, Bond, Bowie, Bush, Bolt, Baldwin,
        Cruise, Clooney, Cyrus, Carey, Craig, Clinton, Chan, Cooper, Chaplin,
        DiCaprio, Depp, Dion, De Niro, Diaz, Drake, Damon, Disney,
        Einstein, Eminem, Eilish, Eastwood, Elton John, Evans,
        Ford, Freeman, Fox, Federer, Franklin, Fallon,
        Gaga, Gomez, Grande, Gates, Gosling, Hanks, Grande,
        Hanks, Hilton, Hemsworth, Houston, Hamilton, Hart, Hayek, Holland,
        Iron Man (Stark), Ibrahimovic,
        Jackson, Jolie, Jordan, Johansson, Jagger, Jackman, Johnson, Jay-Z, Jenner, James,
        Kardashian, Kunis, Kidman, Kutcher, Kennedy, Klum, King, Khalifa,
        Lopez, Lawrence, DiCaprio, Lennon, Lohan, Lima, Lively, Lee, Legend,
        Madonna, Monroe, Messi, Musk, McCartney, Murphy, Marley, Minaj, Mendes,
        Neymar, Norris, Nicholson, Neeson, Newton,
        Obama, Ora, Olsen, Oprah,
        Pitt, Portman, Presley, Pattinson, Perry, Pratt, Pacino, Pele,
        Queen, Quinn,
        Rihanna, Ronaldo, Roberts, Reynolds, Robbie, Radcliffe, Reeves, Ross, Ramsey, Rocky,
        Spears, Swift, Smith, Schwarzenegger, Streep, Stallone, Sheeran, Sandler, Shakira, Stewart,
        Timberlake, Trump, Theron, Travolta, Tyson, Turner, Tatum,
        Usher, Underwood,
        Vader, Vettel, Van Damme,
        Willis, Winslet, Woods, Winfrey, Watson, West, Williams, Wahlberg,
        Xzibit,
        Zuckerberg, Zellweger, Zidane, Zendaya
        """,
        
        // MARK: - Essen & Trinken
        "Bis zu welchem Buchstaben kommst du bei Getränken?": """
        Apfelsaft, Apfelschorle, Altbier, Ayran, Almdudler,
        Bier, Bowle, Buttermilch, Brause, Bubble Tea,
        Cola, Cappuccino, Cider, Champagner, Cocktails, Chai Latte, Cognac,
        Dosenbier, Dr Pepper, Direktsaft,
        Eistee, Espresso, Energy Drink, Eiskaffee,
        Fanta, Fruchtsaft, Federweißer, Fassbrause,
        Gin, Glühwein, Ginger Ale, Grappa, Grüner Tee,
        Heiße Schokolade, Helles, Hugo,
        Ingwertee, Isodrink,
        Johannisbeersaft, Jägermeister,
        Kakao, Kaffee, KiBa, Kölsch, Korn, Kräutertee, Kefir, Kirschsaft,
        Limonade, Latte Macchiato, Likör, Leitungswasser, Lassi,
        Milch, Mineralwasser, Milchshake, Malzbier, Mojito, Mate, Matcha,
        Nektar,
        Orangensaft, Ouzo, Obstler,
        Pils, Prosecco, Punsch, Pfefferminztee, Portwein,
        Quellwasser,
        Radler, Rotwein, Rum, Rosé, Red Bull,
        Saft, Sekt, Schnaps, Spezi, Sprite, Smoothie, Sprudelwasser, Schwarzer Tee, Sake, Sambuca,
        Tee, Tequila, Traubensaft, Tomatensaft, Tonic Water,
        Uzo,
        Vodka, Vitaminwasser,
        Wasser, Wein, Whisky, Weißwein, Weizenbier, Wodka, Wasser ohne Kohlensäure,
        Zitronenlimonade
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Cocktails?": """
        Aperol Spritz, Amaretto Sour, Americano,
        Bloody Mary, Bellini, Bahama Mama, Black Russian,
        Caipirinha, Cosmopolitan, Cuba Libre, Campari Orange, Caipiroska, Colada,
        Daiquiri, Dry Martini, Dark and Stormy,
        Espresso Martini, El Diablo,
        French 75, Flying Kangaroo, Fizz,
        Gin Tonic, Gimlet, Gin Fizz, Grasshopper, Gibson,
        Hugo, Hurricane, Harvey Wallbanger, Highball,
        Ice Tea (Long Island), Irish Coffee,
        Jack and Coke, Julep,
        Kir Royal, Kamikaze,
        Long Island Iced Tea, Lemon Drop, Lynchburg Lemonade,
        Mojito, Margarita, Mai Tai, Martini, Moscow Mule, Manhattan, Mimosa, Mint Julep,
        Negroni,
        Old Fashioned, Orgasm,
        Piña Colada, Planter's Punch, Pimm's Cup, Paloma, Pink Lady,
        Rusty Nail, Rum Sour, Rob Roy,
        Sex on the Beach, Swimming Pool, Singapore Sling, Sazerac, Screwdriver, Spritz, Sour, Sunrise (Tequila),
        Tequila Sunrise, Tom Collins, Touch Down,
        Vodka Lemon, Vodka Bull, Vodka Martini,
        Whisky Sour, White Russian, Woo Woo,
        Zombie
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Gerichten (weltweit)?": """
        Auflauf, Antipasti, Apfelstrudel,
        Bratwurst, Burger, Burrito, Bolognese, Baguette, Bauernfrühstück, Brathähnchen, Bibimbap,
        Currywurst, Chili con Carne, Carbonara, Couscous, Cordon Bleu, Crepes, Ceviche,
        Döner, Dumplings, Dim Sum, Dhal,
        Eintopf, Ente, Enchilada, Eisbein, Eierkuchen,
        Falafel, Fischstäbchen, Flammkuchen, Fondue, Frühlingsrolle, Frikadelle, Fajitas, Fish and Chips,
        Gulasch, Gratin, Gyros, Gazpacho, Guacamole, Gemüsesuppe, Germknödel,
        Hamburger, Hot Dog, Hummus, Hähnchen,
        Insalata Caprese, Irish Stew,
        Jägerschnitzel, Jambalaya,
        Kartoffelsalat, Knödel, Kebab, Kaiserschmarrn, Königsberger Klopse, Kartoffelpuffer, Kimchi, Kässpätzle,
        Lasagne, Linsensuppe, Leberkäse, Labskaus,
        Maultaschen, Mac and Cheese, Moussaka, Minestrone, Milchreis, Masala,
        Nudeln, Nachos, Nasi Goreng, Nugget,
        Omelett, Ofenkartoffel, Ossobuco,
        Pizza, Pasta, Pfannkuchen, Paella, Pommes, Pad Thai, Pesto, Peking Ente, Pierogi, Poke Bowl,
        Quiche, Quesadilla, Quarkbällchen,
        Risotto, Ramen, Raclette, Ratatouille, Rouladen, Ravioli, Reibekuchen, Rostbratwurst,
        Schnitzel, Sushi, Spaghetti, Salat, Suppe, Steak, Sauerbraten, Sommerrollen, Shakshuka, Samosa, Spätzle,
        Tacos, Tapas, Tiramisu, Tortellini, Tofu, Tomatensuppe, Tikka Masala,
        Udon,
        Viennoise (Schnitzel), Vindaloo,
        Wiener Schnitzel, Waffeln, Wrap, Wurstsalat, Wantan,
        Yakitori,
        Zwiebelrostbraten, Zwiebelsuppe
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Fast-Food-Ketten?": """
        Arby's, Applebee's,
        Burger King, BackWerk, Block House, Buffalo Wild Wings, Baskin-Robbins,
        Chick-fil-A, Chipotle, Costa Coffee, Carl's Jr., Chidoba,
        Dunkin' Donuts, Domino's Pizza, Dean & David, Dairy Queen,
        Einstein Bros. Bagels,
        Five Guys, Freddy Fresh,
        Greggs,
        Hard Rock Cafe, Hooters, Hans im Glück, Hallo Pizza, Haferkater,
        In-N-Out Burger, IHOP,
        Jack in the Box, Joe & The Juice, Jim Block,
        KFC (Kentucky Fried Chicken), Krispy Kreme, Kochlöffel,
        Little Caesars, Le Crobag, L'Osteria,
        McDonald's, Maredo, MoschMosch, McCafé,
        Nordsee, Nandos,
        Outback Steakhouse,
        Pizza Hut, Papa John's, Popeyes, Pret A Manger, Panera Bread, Panda Express, Peter Pane,
        Quiznos,
        Red Lobster,
        Subway, Starbucks, Sausalitos, Shake Shack, Sonic, Sbarro,
        Taco Bell, Tim Hortons, TGI Fridays, Tchibo, The Cheesecake Factory,
        Vapiano,
        Wendy's, Whataburger, White Castle, Wienerwald, Wonder Waffel,
        Yormas,
        Zaxby's
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Gewürzen?": """
        Anis,
        Basilikum, Bohnenkraut, Bärlauch, Bockshornklee,
        Chili, Curry, Cayennepfeffer, Cumin (Kreuzkümmel), Cardamom,
        Dill,
        Estragon,
        Fenchel,
        Gewürznelke,
        Ingwer,
        Kardamom, Knoblauch, Koriander, Kümmel, Kurkuma, Kerbel, Kreuzkümmel, Kräuter der Provence,
        Lorbeer, Liebstöckel, Lavendel,
        Majoran, Muskatnuss, Minze, Meerrettich, Mohn,
        Nelke,
        Oregano,
        Pfeffer, Paprika, Petersilie, Piment,
        Rosmarin,
        Safran, Salz, Schnittlauch, Sternanis, Senfkörner, Salbei, Sambal Oelek, Sesam, Sumach,
        Thymian,
        Vanille,
        Wacholder, Wasabi,
        Zimt, Zitronengras, Zwiebelpulver, Zucker
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Käsesorten?": """
        Appenzeller, Allgäuer Bergkäse,
        Brie, Bergkäse, Butterkäse, Büffelmozzarella, Blauschimmelkäse, Babybel, Burrata,
        Camembert, Cheddar, Chester, Comté, Cottage Cheese,
        Danablu, Doppelrahmfrischkäse,
        Edamer, Emmentaler, Esrom,
        Feta, Frischkäse, Fonduekäse, Fontina,
        Gorgonzola, Gouda, Gruyère, Gauda, Grünländer,
        Harzer Roller, Halloumi, Havarti, Hüttenkäse, Heilbutt,
        Italienischer Hartkäse,
        Jarlsberg, Junger Gouda,
        Käse, Kochkäse, Kräuterkäse,
        Leerdammer, Limburger,
        Maasdammer, Mozzarella, Mascarpone, Manouri, Manchego, Mittelalter Gouda, Morbier, Münsterkäse,
        Neufchâtel,
        Obazda, Ofenkäse, Old Amsterdam,
        Parmesan, Pecorino, Provolone, Paneer,
        Quark, Quäse,
        Raclettekäse, Ricotta, Roquefort, Romadur, Reibekäse, Rohmilchkäse,
        Schafskäse, Schmelzkäse, Schnittkäse, Stilton, Streichkäse, Sauermilchkäse,
        Tilsiter, Trappistenkäse, Tetilla,
        Vacherin,
        Weichkäse, Weißschimmelkäse, Westfale,
        Ziegenkäse, Ziger
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Brotsorten?": """
        Alpenbrot,
        Bauernbrot, Baguette, Brötchen, Brezel, Brioche, Butterzopf, Brot, Bagel,
        Ciabatta, Croissant,
        Dinkelbrot, Doppelback, Dönerbrot,
        Eiweißbrot,
        Fladenbrot, Franzbrötchen, Focaccia, Früchtebrot,
        Graubrot, Gersterbrot, Gewürzbrot, Graham-Brot,
        Hefezopf, Haferbrot, Holzofenbrot,
        Ingwerbrot,
        Kartoffelbrot, Knäckebrot, Körnerbrot, Kastenbrot, Krustenbrot, Kürbiskernbrot, Kommissbrot,
        Landbrot, Laugenbrezel, Laugenbrötchen, Landbrot,
        Mehrkornbrot, Mischbrot, Maisbrot, Milchbrötchen, Matzen,
        Naan, Nussbrot,
        Olivenbrot, Osterbrot,
        Pita, Pumpernickel, Panini, Pide, Pizzateig, Pausenbrot,
        Quarkbrot,
        Roggenbrot, Rosinenbrot, Roggenmischbrot, Röstbrot,
        Schwarzbrot, Sauerteigbrot, Sonnenblumenkernbrot, Stuten, Semmel, Schrippe, Sandwich, Softbrötchen,
        Toast, Toastbrot, Tortilla,
        Vollkornbrot, Vinschgauer, Vitalbrot,
        Weißbrot, Weizenbrot, Weltmeisterbrötchen, Weizenmischbrot, Walnussbrot,
        Zopfbrot, Zwiebelbrot, Zwieback
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Frühstücks-Sachen?": """
        Apfel, Aufschnitt, Ananas, Avocado,
        Brot, Brötchen, Butter, Brezel, Bagel, Banane, Birne, Blaubeeren, Bacon, Baked Beans,
        Cornflakes, Croissant, Cappuccino, Crepes, Cerealien, Chia-Pudding,
        Dinkelbrot, Donut,
        Eier, Eiweiß, Erdbeermarmelade, Espresso, Englisch Breakfast, Eierbecher,
        Frischkäse, Fruchtsaft, Früchte, French Toast, Fruchtjoghurt,
        Grapefruit, Gurke, Granola, Grüner Tee,
        Honig, Haferflocken, Haferbrei, Himbeeren, Haselnusscreme, Hefezopf,
        Ingwertee, Ingwer-Shot,
        Joghurt, Johannisbeeren,
        Kaffee, Käse, Kakao, Knäckebrot, Kiwi, Kornflakes, Ketchup (zu Eiern),
        Lachs, Latte Macchiato, Leberwurst, Laugenstange, Limonade,
        Marmelade, Milch, Müsli, Mandarinen, Melone, Muffin, Milchkaffee, Margarine, Mozzarella,
        Nutella, Nüsse, Nougatcreme,
        Obst, Orangensaft, Omelett, Obstsalat, Oliven,
        Pfannkuchen, Porridge, Pancakes, Pumpernickel, Paprika, Pfefferminztee, Pudding,
        Quark,
        Rührei, Rosinenbrötchen, Radieschen, Rohkost, Räucherlachs,
        Schinken, Salami, Saft, Salz, Semmel, Spiegelei, Speck, Smoothie, Sirup, Schokomüsli, Schwarzbrot, Schnittlauch, Senf, Sahne,
        Tee, Toast, Tomate, Trauben, Teewurst,
        Vollkornbrot, Vanillejoghurt,
        Waffeln, Weiches Ei, Wurst, Wasser, Weintrauben, Weißbrot,
        Zucker, Zwieback, Zimtschnecke, Zitrone
        """,
        
        // MARK: - Orte & Reisen
        "Bis zu welchem Buchstaben kommst du bei Urlaubsländern?": """
        Ägypten, Australien, Amerika, Albanien, Argentinien,
        Belgien, Brasilien, Bulgarien, Bali (Indonesien), Bahamas,
        China, Costa Rica, Chile,
        Dänemark, Deutschland, Dominikanische Republik, Dubai (VAE),
        England, Ecuador,
        Frankreich, Finnland, Fidschi,
        Griechenland, Großbritannien,
        Holland,
        Italien, Indien, Irland, Island, Indonesien, Israel,
        Jamaika, Japan, Jordanien,
        Kanada, Kroatien, Kenia, Kuba, Kolumbien, Kap Verde,
        Luxemburg,
        Malta, Marokko, Mexiko, Malediven, Malaysia, Mauritius, Monaco,
        Niederlande, Neuseeland, Norwegen, Nepal,
        Österreich, Oman,
        Portugal, Polen, Peru, Philippinen, Panama,
        Russland, Rumänien,
        Spanien, Schweden, Schweiz, Südafrika, Seychellen, Sri Lanka, Singapur, Schottland,
        Türkei, Thailand, Tunesien, Tschechien, Tansania,
        Ungarn, USA,
        Vietnam, Vereinigte Arabische Emirate,
        Zypern
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Inseln?": """
        Amrum, Aruba, Australien, Azoren,
        Borkum, Bali, Borneo, Bahamas, Barbados, Baltrum, Bornholm,
        Curacao, Capri, Canaren, Cuba, Ceylon (Sri Lanka),
        Dominica,
        Elba, England,
        Fehmarn, Fidschi, Fuerteventura, Formentera, Föhr,
        Gran Canaria, Grönland, Galapagos, Gozo,
        Hawaii, Helgoland, Hiddensee, Haiti, Honshu,
        Ibiza, Island, Irland, Ischia,
        Jamaika, Java, Juist, Japan,
        Kreta, Korsika, Kuba, Korfu, Kos, Kap Verde,
        Langeoog, La Gomera, Lanzarote, La Palma, Long Island,
        Mallorca, Malta, Madagaskar, Menorca, Madeira, Mykonos, Maui, Malediven, Mauritius, Manhattan, Mainau,
        Norderney, Neuseeland, Neuguinea, Neuwerk,
        Oahu,
        Phuket, Pellworm,
        Rügen, Rhodos, Römö, Reunion,
        Sylt, Sardinien, Sizilien, Spiekeroog, Sri Lanka, Sumatra, Santorin, Seychellen, Samoa, Samos, St. Lucia,
        Teneriffa, Tasmanien, Tahiti, Texel, Trinidad, Timor,
        Usedom,
        Vancouver Island,
        Wangerooge,
        Zypern, Zanzibar
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Sehenswürdigkeiten?": """
        Akropolis, Alexanderplatz, Ayers Rock, Alhambra, Alpen, Angkor Wat,
        Big Ben, Brandenburger Tor, Burj Khalifa, Berliner Mauer, Blaue Moschee, Buckingham Palace, Brooklyn Bridge,
        Chinesische Mauer, Checkpoint Charlie, Colosseum, Cristo Redentor, Chichén Itzá, CN Tower,
        Dom zu Köln, Disney World, Denkmäler, Dresdner Frauenkirche,
        Eiffelturm, Empire State Building, Elbphilharmonie, Eremitage,
        Freiheitsstatue, Fernsehturm, Forum Romanum, Fujiyama, Frauenkirche,
        Golden Gate Bridge, Grand Canyon, Great Barrier Reef, Gizeh Pyramiden,
        Hollywood Sign, Hofbräuhaus, Hagia Sophia, Himalaya, Holstentor,
        Isartor,
        Jungfraujoch,
        Kölner Dom, Kreml, Kolosseum, Kap der Guten Hoffnung,
        Louvre, Leuchtturm, London Eye, Loch Ness, Las Vegas Strip,
        Machu Picchu, Matterhorn, Mount Everest, Mauer (China), Museumsinsel, Manneken Pis, Monument Valley,
        Niagarafälle, Notre Dame, Neuschwanstein, Nordkap, Nationalpark,
        Oktoberfest, Oper von Sydney,
        Pyramiden, Prater, Petersdom, Parthenon, Pompeji, Petra, Porta Nigra,
        Reichstag, Rotes Meer, Riesenrad, Rocky Mountains,
        Schloss Neuschwanstein, Stonehenge, Freiheitsstatue, Schiefer Turm von Pisa, Semperoper, Sydney Opera House, Sagrada Familia, Sanssouci,
        Taj Mahal, Times Square, Tower Bridge, Tafelberg, Triumphbogen, Titanic Museum,
        Uluru, Universal Studios,
        Vatikan, Versailler Schloss, Venedig Kanäle, Victoriafälle,
        Weißes Haus, World Trade Center, Westminster Abbey, Wall Street, Wattenmeer,
        Yellowstone,
        Zugspitze
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Bergen?": """
        Alpen, Andes, Annapurna, Aconcagua, Ararat, Atlas,
        Brocken, Blanc (Mont), Ben Nevis,
        Chimborazo,
        Denali (Mount McKinley), Dolomiten, Dachstein,
        Elbrus, Eiger, Everest, Etna,
        Feldberg, Fujiyama, Fichtelberg,
        Großglockner, Gran Sasso,
        Himalaya, Harz, Heilige Berge, Hohe Tatra,
        Inselsberg,
        Jungfrau, Jura,
        Kilimandscharo, K2, Karwendel, Kaukasus, Kosciuszko,
        Lhotse,
        Matterhorn, Mount Everest, Mont Blanc, Makalu, Mount Kenya, Marmolada, Mönch,
        Nanga Parbat, Nebelhorn,
        Olymp, Ortler,
        Pikes Peak, Pyrenäen, Pilatus, Popocatepetl,
        Rigi, Rocky Mountains, Rax,
        Schwarzwald, Säntis, Sierra Nevada, Snowdon, Scafell Pike, Stromboli,
        Tafelberg, Titlis, Teide, Triglav, Tatra,
        Ural, Uluru,
        Vesuv, Vogesen, Vinson,
        Watzmann, Wasserkuppe, Weisshorn, Whitney (Mount),
        Zugspitze
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Meeren oder Ozeanen?": """
        Adria, Atlantik, Arabisches Meer, Ägäis, Arktischer Ozean,
        Beringmeer, Baltisches Meer (Ostsee), Boden-See (See, aber Wasser),
        Chinesisches Meer,
        Dardanellen,
        Eismeer, Europäisches Nordmeer,
        Golf von Mexiko, Gelbes Meer,
        Hudson Bay,
        Indischer Ozean, Indik,
        Japanisches Meer,
        Karibik, Kaspisches Meer, Korallenmeer,
        Mittelmeer, Marmarameer,
        Nordsee, Nordpolarmeer,
        Ostsee, Ozean,
        Pazifik, Persischer Golf, Pazifischer Ozean, Polarmeer,
        Rotes Meer, Rossmeer,
        Schwarzes Meer, Südpolarmeer, Sargassosee, Südsee,
        Tasmansee, Totes Meer (See), Tyrrhenisches Meer,
        Weddell-Meer, Weißes Meer
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Flughäfen (Stadt/Name)?": """
        Amsterdam (Schiphol), Atlanta, Athen, Antalya, Abu Dhabi,
        Berlin, Bangkok, Boston, Barcelona, Brüssel, Budapest, Bremen, Beijing,
        Chicago, Charles de Gaulle (Paris), Charlotte, Cancún, Cincinnati,
        Dubai, Dallas, Denver, Düsseldorf, Dublin, Doha, Delhi, Detroit, Dresden,
        Ezeiza (Buenos Aires), Edinburgh, Entebbe,
        Frankfurt, Fiumicino (Rom), Faro, Florenz,
        Gatwick (London), Genf, Guangzhou, Glasgow,
        Heathrow (London), Hamburg, Hongkong, Hartsfield-Jackson, Houston, Helsinki, Hannover, Hurghada,
        Istanbul, Incheon (Seoul), Ibiza,
        JFK (New York), Johannesburg, Jakarta,
        Kopenhagen, Köln-Bonn, Kuala Lumpur, Keflavik, Kairo,
        London, Los Angeles, Lissabon, Las Vegas, LaGuardia, Leipzig, Lyon, Luton,
        München, Madrid, Miami, Mailand, Manchester, Moskau, Melbourne, Manila, Mexiko-Stadt, Mumbai, Mallorca (Palma),
        New York, Newark, Narita (Tokio), Nizza, Nashville,
        Orly (Paris), Oslo, O'Hare (Chicago), Orlando, Osaka,
        Paris, Peking, Palma de Mallorca, Philadelphia, Phoenix, Prag, Perth, Porto,
        Qatar (Doha),
        Rom, Rio de Janeiro, Reykjavik,
        Singapur (Changi), Sydney, San Francisco, Seattle, Shanghai, Seoul, Stuttgart, Stansted, Stockholm, Schiphol,
        Tokio, Toronto, Tegel (ehem.), Taipeh, Tel Aviv, Teneriffa,
        Wien, Washington, Warschau,
        Zürich
        """,
        
        // MARK: - Unterhaltung & Medien
        "Bis zu welchem Buchstaben kommst du bei Filmtiteln?": """
        Avatar, Avengers, Alien, American Pie, Aladdin, Armageddon, Aquaman, Alice im Wunderland, Alles steht Kopf,
        Barbie, Batman, Black Panther, Blade Runner, Braveheart, Bad Boys, Bambi, Back to the Future,
        Cars, Casino Royale, Coco, Captain America, Catch Me If You Can, Cinderella, Conjuring, Creed, Chicago,
        Die Hard (Stirb Langsam), Dune, Django Unchained, Dirty Dancing, Der Pate, Deadpool, Dr. Strange, Dumbo, Der König der Löwen, Das Dschungelbuch,
        E.T., Erin Brockovich, Elementals, Encanto, Ex Machina,
        Forrest Gump, Fast & Furious, Frozen (Die Eiskönigin), Fight Club, Findet Nemo, Fack ju Göhte, Footloose,
        Gladiator, Ghostbusters, Godzilla, Goodfellas, Gravity, Grease, Guardians of the Galaxy, Green Mile, Get Out,
        Harry Potter, Herr der Ringe, Hunger Games, Hangover, Home Alone (Kevin allein zu Haus), Hulk, Halloween, Honig im Kopf, Hotel Transsilvanien,
        Interstellar, Inception, It (Es), Iron Man, Indiana Jones, Ice Age, I Am Legend, Inglourious Basterds, Inside Out,
        Jurassic Park, Jumanji, Joker, John Wick, James Bond, Jaws (Der Weiße Hai),
        King Kong, Kill Bill, Karate Kid, Kung Fu Panda, König der Löwen, Keinohrhasen,
        La La Land, Lord of the Rings, Leon der Profi, Logan, Life of Pi, Lilo & Stitch,
        Matrix, Minions, Mamma Mia, Mission Impossible, Mad Max, Men in Black, Mulan, Moana, Marvels,
        Nemo, Notting Hill, No Time to Die, Nightmare Before Christmas, Napoleon,
        Oppenheimer, Ocean's Eleven, Oldboy,
        Pulp Fiction, Pirates of the Caribbean (Fluch der Karibik), Parasite, Psycho, Pretty Woman, Peter Pan, Planet der Affen, Pitch Perfect, Poltergeist,
        Quiet Place, Quantum of Solace,
        Rocky, Rambo, Ratatouille, Reservoir Dogs, Rain Man, Rio, Rapunzel, Robin Hood,
        Star Wars, Spider-Man, Shrek, Scarface, Schindler's Liste, Saw, Scream, Seven, Superman, Skyfall, Soul, Sonic,
        Titanic, Terminator, The Dark Knight, Top Gun, Toy Story, Twilight, Thor, Transformers, The Godfather, The Matrix, Tenet, Taxi Driver,
        Up (Oben), Underworld, Uncharted,
        Venom, Vaterfreuden, Vaiana, Vertigo,
        Wall-E, Wonder Woman, Wolf of Wall Street, Wickie, Wonka, West Side Story,
        X-Men, XXX,
        Yesterday, You've Got Mail,
        Zootopia, Zombieland, Zurück in die Zukunft
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Serien?": """
        Avatar, Aktenzeichen XY, American Horror Story, Andor, A-Team, Arrow, Arcane,
        Breaking Bad, Big Bang Theory, Bridgerton, Brooklyn Nine-Nine, Black Mirror, Better Call Saul, Buffy, Bones, Baywatch, Bluey,
        Chernobyl, Crown, Castle, Criminal Minds, Cobra Kai, Charmed, Community, Chicago Fire,
        Dark, Dexter, Desperate Housewives, Downton Abbey, Dr. House, Daredevil, Dragon Ball, Denver Clan, Doctor Who,
        Euphoria, Elite, Elementary, Entourage,
        Friends, Family Guy, Fargo, Fleabag, Fuller House, Fresh Prince, Futurama, Firefly,
        Game of Thrones, Grey's Anatomy, Gilmore Girls, Glee, Gossip Girl, Good Doctor, Gute Zeiten Schlechte Zeiten, Golden Girls,
        House of Cards, How I Met Your Mother, Homeland, Haus des Geldes, Hawaii Five-0, Hannibal, Heroes, Heartstopper,
        iCarly, In aller Freundschaft, Invincible, It's Always Sunny in Philadelphia,
        Jeriks, Jessica Jones,
        King of Queens, Knight Rider, Keeping Up with the Kardashians, Killing Eve, Kommissar Rex,
        Lost, Loki, Lucifer, Law & Order, Lindenstraße, Lupin, Last of Us, Löwenzahn,
        Modern Family, Mandalorian, Money Heist, Mr. Bean, Mad Men, Monk, MacGyver, Malcom mittendrin, Moon Knight, Mindhunter,
        Narcos, NCIS, New Girl, Nanny, Navy CIS,
        Office (The), Outlander, Ozark, One Piece, Orange Is the New Black, Outer Banks, Only Murders in the Building, Obi-Wan Kenobi,
        Prison Break, Peaky Blinders, Pokemon, Pretty Little Liars, Parks and Recreation, Paw Patrol, Punisher,
        Queen's Gambit,
        Rick and Morty, Riverdale, Reacher, Rome, Rosenheim-Cops,
        Stranger Things, Suits, Simpsons, Squid Game, Star Trek, Sherlock, Scrubs, South Park, Supernatural, Sex and the City, Stromberg, Shameless, Sons of Anarchy, Seinfeld, SpongeBob, Star Wars: The Clone Wars, Succession, Severance,
        The Walking Dead, The Wire, True Detective, Two and a Half Men, Tatort, The Boys, Ted Lasso, The Last of Us, The Crown, This Is Us, The Witcher, Teen Wolf, Twin Peaks,
        Umbrella Academy, Unter Uns,
        Vampire Diaries, Vikings, Veep, Veronica Mars,
        Wednesday, Witcher, Walking Dead, Westworld, WandaVision, What If...?, Winx Club, Will & Grace,
        X-Files (Akte X), Xena,
        Yellowstone, You, Young Sheldon,
        Zelda
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Videospielen?": """
        Animal Crossing, Assassin's Creed, Apex Legends, Among Us, Age of Empires, Ark, Alan Wake, Angry Birds,
        Battlefield, Bioshock, Borderlands, Bloodborne, Baldur's Gate, Brawl Stars, Bomberman, Batman Arkham,
        Call of Duty, Counter-Strike, Cyberpunk 2077, Civilization, Crash Bandicoot, Candy Crush, Clash of Clans, Castlevania, Crysis, Cities: Skylines, Cuphead,
        Diablo, Doom, Dota 2, Dark Souls, Destiny, Donkey Kong, Dead by Daylight, Dead Space, Dragon Age, Detroit: Become Human, Death Stranding, Deus Ex,
        Elden Ring, Elder Scrolls, EA Sports FC, Earthbound, Escape from Tarkov, Eve Online,
        Fortnite, FIFA, Final Fantasy, Fallout, Far Cry, Forza Horizon, Fire Emblem, Five Nights at Freddy's, F-Zero, Farming Simulator,
        GTA (Grand Theft Auto), God of War, Gran Turismo, Genshin Impact, Gears of War, Ghost of Tsushima, Guitar Hero, Guild Wars, Gothic, Garry's Mod,
        Halo, Half-Life, Hitman, Horizon Zero Dawn, Hogwarts Legacy, Hollow Knight, Hades, Hearthstone, Heavy Rain, Heroes of Might and Magic,
        It Takes Two, Inside, Injustice,
        Just Dance, Journey, Jak and Daxter, Jedi: Fallen Order,
        Kingdom Hearts, Kirby, Kraft, Kart,
        League of Legends, Legend of Zelda, Last of Us, Left 4 Dead, LittleBigPlanet, Life is Strange, Limbo, Lego Star Wars, Luigi's Mansion,
        Minecraft, Mario Kart, Mario Party, Metal Gear Solid, Mass Effect, Monster Hunter, Mortal Kombat, Mega Man, Metroid, Mafia, Max Payne, Monkey Island, Madden NFL, Microsoft Flight Simulator,
        Need for Speed, NBA 2K, Nier: Automata, No Man's Sky, Nintendogs, Naruto,
        Overwatch, Oblivion, Outlast, Ori and the Blind Forest, Overcooked,
        Pokémon, PUBG, Portal, Pac-Man, Persona, Plants vs. Zombies, Prince of Persia, Payday, Palworld,
        Quake,
        Red Dead Redemption, Resident Evil, Roblox, Rocket League, Rainbow Six Siege, Ratchet & Clank, Rayman, RimWorld, Rust, Returnal,
        Super Mario, Sims, Skyrim, Sonic, Street Fighter, Spider-Man, Star Wars Battlefront, Stardew Valley, Sea of Thieves, Splatoon, Spyro, Sekiro, Silent Hill, StarCraft, Subnautica, Super Smash Bros, SimCity, Skate, Saints Row, Civilization,
        Tetris, The Witcher, Tomb Raider, Tekken, Team Fortress 2, Terraria, Titanfall, The Last of Us, Tony Hawk, Trackmania,
        Uncharted, Undertale, Until Dawn, Uno,
        Valorant, Valheim,
        World of Warcraft, Witcher, Wii Sports, Wolfenstein, Watch Dogs, Warframe, Worms, WarioWare, World of Tanks,
        Xenoblade Chronicles, XCOM,
        Yakuza, Yoshi's Island,
        Zelda
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Superhelden?": """
        Aquaman, Ant-Man, Avengers, Arrow,
        Batman, Black Panther, Black Widow, Batgirl, Blade, Beast Boy, Blue Beetle, Bucky Barnes,
        Captain America, Captain Marvel, Catwoman, Cyborg, Cyclops, Colossus,
        Daredevil, Dr. Strange, Deadpool, Doktor Fate, Drax,
        Elektra, Elastigirl,
        Flash, Fantastic Four, Falcon, Frozone,
        Green Lantern, Green Arrow, Groot, Gamora, Ghost Rider, Gambit, Guardians of the Galaxy,
        Hulk, Hawkeye, Hellboy, Human Torch (Menschliche Fackel), He-Man, Hancock,
        Iron Man, Invisible Woman (Die Unsichtbare), Iceman, Iron Fist, Incredibles, Invincible,
        Jean Grey, Joker (eher Bösewicht, aber oft genannt), Jessica Jones, Jubilee, Justice League,
        Kick-Ass,
        Luke Cage, Loki (Antiheld), Lantern,
        Moon Knight, Mr. Incredible, Magneto, Martian Manhunter, Miles Morales, Ms. Marvel, Mystique,
        Nightwing, Nick Fury, Namor, Nebula, Ninja Turtles,
        One Punch Man,
        Punisher, Power Rangers, Professor X, Phantom, Phoenix, Plastic Man,
        Quicksilver,
        Robin, Rogue, Rocket Raccoon, Rorschach, Red Guardian, Raven,
        Spider-Man, Superman, Supergirl, Scarlet Witch, Shazam, Storm, Silver Surfer, Star-Lord, She-Hulk, Spawn, Shang-Chi, Saitama,
        Thor, The Flash, Thing (Das Ding), Teenage Mutant Ninja Turtles, Thanos,
        Vision, Venom (Antiheld), Valkyrie,
        Wonder Woman, Wolverine, Wasp, Winter Soldier, War Machine, Watchmen,
        X-Men, Xavier, X-23,
        Yondu, Yellowjacket,
        Zorro
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Bösewichten (Film/Serie)?": """
        Agent Smith, Alien,
        Bane, Bowser, Bill Cipher, Blofeld, Bellatrix Lestrange, Biff Tannen,
        Cruella de Vil, Captain Hook, Chucky, Cell, Cersei Lannister, Count Dooku, Carnage,
        Darth Vader, Dr. Evil, Dr. Octopus, Dementor, Davy Jones, Dracula, Doomsday, Darkseid, Dr. Doom,
        Electro, Emperor Palpatine, Evil Queen,
        Freddy Krueger, Frieza, Frank Underwood,
        Green Goblin, Gaston, Ganondorf, Gollum, General Grievous, Grindelwald, Gus Fring, Ghostface, General Zod,
        Hannibal Lecter, Hades, Hans Gruber, Hela, Homelander, Hydra, Harley Quinn, Hook,
        It (Pennywise), Iago, Imperator,
        Joker, Jafar, Jason Voorhees, Jigsaw,
        Kingpin, Khan, Kylo Ren, Kang, Killmonger, Krusty der Clown, Kraken,
        Loki, Lord Voldemort, Lex Luthor, Leatherface, Lucifer, Lotso,
        Magneto, Maleficent, Megatron, Michael Myers, Moriarty, Mysterio, Mystique, Maul (Darth), Majin Buu, Mr. Burns,
        Negan, Norman Bates, Night King, Nosferatu,
        Octopus, Orochimaru,
        Pennywise, Palpatine, Predator, Penguin, Poison Ivy, Plankton,
        Queen of Hearts,
        Riddler, Red Skull, Reverse Flash, Ronan, Ramsay Bolton,
        Sauron, Scar, Shredder, Saruman, Smaug, Snape, Syndrome, Sandman, Sephiroth, Shere Khan, Skeletor, Stormtrooper, Sith,
        Thanos, Terminator, T-1000, Two-Face, Team Rocket, The Grinch,
        Ultron, Ursula, Umbridge, Unicron,
        Voldemort, Venom, Vader, Vecna, Vulture,
        Wicked Witch, Walter White, Wile E. Coyote,
        Xenomorph,
        Zod, Zurg
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Rappern (Vorname)?": """
        Apache 207, Alligatoah, Asap Rocky, Akon, Azad, Ali Bumaye, Animus, Azet,
        Bushido, Bausa, Bonez MC, Biggie Smalls, B-Tight, Badmómzjay, Bass Sultan Hengdt,
        Capital Bra, Cro, Cardi B, Casper, Coolio, Chance the Rapper, Celo, Capo,
        Drake, Dr. Dre, DMX, Daddy Yankee, Doja Cat, Dardan, Deichkind, Dendemann, Data Luv,
        Eminem, Eko Fresh, Eno, Eazy-E,
        Farid Bang, Fifty Cent (50 Cent), Fler, Fat Joe, Fergie, Fero47, Finna, Favorite, Future, Flo Rida,
        Gzuz, Gucci Mane, G-Eazy, Gentleman, Greeen, Haftbefehl,
        Haftbefehl, Hanybal,
        Ice Cube, Ice-T, Iggy Azalea,
        Jay-Z, Juice WRLD, J. Cole, Jamule, Juju,
        Kanye West, Kendrick Lamar, Kollegah, Kontra K, Kool Savas, KC Rebell, Katja Krasavice, K.I.Z., Kurdo, Kalim,
        Lil Wayne, Lil Nas X, Luciano, Loredana, Logic, Ludacris, LL Cool J,
        Mac Miller, Macklemore, Marteria, Megan Thee Stallion, Mero, Metrickz, Money Boy, Machine Gun Kelly, Mos Def, Maxwell, Manuellsen, Motrip,
        Nimo, Nicki Minaj, Nas, Notorious B.I.G., Nelly, Nate57, Nura,
        Olexesh, Offset, Outkast,
        Post Malone, Pitbull, Pashanim, Prinz Pi, Peter Fox, P. Diddy, Pusha T, PA Sports,
        Quavo,
        Raf Camora, Rin, Rick Ross, Reezy,
        Sido, Snoop Dogg, Samra, Shindy, Summer Cem, Shirin David, Sean Paul, Ski Aggu, Sun Diego, SSIO, Stormzy, Savas, Silla,
        Travis Scott, Tupac (2Pac), Tyga, T-Low, Trettmann, Timbaland, The Weeknd, Tyler the Creator, T-Pain,
        Ufo361, Usher,
        Veysel,
        Wiz Khalifa, Will Smith, Wu-Tang Clan, Weekend,
        Xatar, XXXTentacion, Xzibit,
        Yung Hurn, Ye (Kanye),
        Zuna
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Bands?": """
        ABBA, AC/DC, Aerosmith, Arctic Monkeys, AnnenMayKantereit, Ärzte,
        Beatles, Backstreet Boys, Bon Jovi, Blink-182, BTS, Black Sabbath, Black Eyed Peas, Beach Boys, Bee Gees, Blur,
        Coldplay, Culcha Candela, Clash, Cranberries, Cure, Creedence Clearwater Revival, Chicago,
        Depeche Mode, Doors, Daft Punk, Deep Purple, Dire Straits, Die Ärzte, Die Toten Hosen, Destiny's Child, Duran Duran,
        Eagles, Earth, Wind & Fire, Evanescence, Electric Light Orchestra,
        Foo Fighters, Fleetwood Mac, Fall Out Boy, Franz Ferdinand, Fettes Brot, Fantastischen Vier,
        Guns N' Roses, Green Day, Genesis, Gorillaz, Good Charlotte, Grateful Dead,
        Imagine Dragons, Iron Maiden, INXS,
        Jackson 5, Journey, Jonas Brothers, Judas Priest, Jethro Tull, Juli,
        Kiss, Kraftwerk, Kings of Leon, Korn, Killers, Kelly Family, K.I.Z., Kraftklub,
        Linkin Park, Led Zeppelin, Limp Bizkit, Little Mix, Lynyrd Skynyrd, Lukas Graham,
        Metallica, Maroon 5, Måneskin, Muse, Modern Talking, Megadeth, Mumford & Sons, My Chemical Romance, Motörhead, Monrose,
        Nirvana, Nickelback, No Doubt, Nightwish, NSYNC, Nine Inch Nails,
        Oasis, One Direction, OneRepublic, Offspring, Outkast,
        Pink Floyd, Pearl Jam, Police, Paramore, Panic! at the Disco, Pur, Pixies, Pussycat Dolls, Prodigy, Placebo, Pentatonix,
        Queen, Queens of the Stone Age,
        Rolling Stones, Red Hot Chili Peppers, Rammstein, Radiohead, Ramones, REM, Rage Against the Machine, Roxy Music, Rosenstolz, Roxette,
        Spice Girls, Scorpions, Strokes, System of a Down, Slipknot, Simon & Garfunkel, Soundgarden, Sex Pistols, Slayer, Santana, Silbermond, Sportfreunde Stiller, Seeed, SDP, Simply Red, Smashing Pumpkins, Status Quo, Sunrise Avenue, Supremes, Swedish House Mafia,
        Tokio Hotel, The Who, The Beatles, The Cure, Twenty One Pilots, Toto, Take That, Tic Tac Toe, Tenacious D, Twisted Sister, The Smiths, Talking Heads, Tears for Fears,
        U2, UB40, Uriah Heep,
        Van Halen, Velvet Underground, Verve,
        Weezer, Westlife, White Stripes, Who, Wu-Tang Clan, Wir sind Helden, Wham!,
        X-Japan,
        Yes, Yardbirds,
        ZZ Top
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Songs (Titel)?": """
        All I Want for Christmas Is You, Angels, Atemlos, As It Was, Africa, Another One Bites the Dust, A Sky Full of Stars, Anti-Hero,
        Bohemian Rhapsody, Baby, Bad Guy, Billie Jean, Blinding Lights, Born in the USA, Beat It, Believer, Blank Space, Back in Black, Barbie Girl, Bitter Sweet Symphony,
        Crazy in Love, Call Me Maybe, Creep, Candle in the Wind, Chandelier, Calm Down, Cold Heart, Can't Stop the Feeling, Careless Whisper, Count on Me, Country Roads,
        Dancing Queen, Despacito, Dance Monkey, Don't Stop Believin', Driver's License, Dynamite, Diamonds, Don't Stop Me Now, Dog Days Are Over,
        Easy on Me, Eye of the Tiger, Empire State of Mind, Every Breath You Take, Earth Song, Enjoy the Silence, Everybody, Enter Sandman,
        Flowers, Firework, Fade to Black, Fix You, Feel Good Inc., Fast Car, Fortnight, Free Bird, Friday I'm in Love,
        Gangnam Style, Girls Just Want to Have Fun, Grenade, God's Plan, Good 4 U, Get Lucky, Go Your Own Way, Golden Hour,
        Happy, Hello, Hey Jude, Hotel California, Hallelujah, Heroes, Halo, Hotline Bling, Havana, Heat Waves, Highway to Hell, Hey Ya!, How Deep Is Your Love,
        I Will Always Love You, Imagine, I Gotta Feeling, In the End, I Want to Hold Your Hand, I Kissed a Girl, It's My Life, Iris, I'm Still Standing,
        Jailhouse Rock, Jolene, Just Dance, Just the Way You Are, Jump, Jessie's Girl,
        Killing Me Softly, Kiss, Karma, Kings & Queens, Knockin' on Heaven's Door, Kung Fu Fighting, Kryptonite,
        Last Christmas, Let It Be, Like a Prayer, Lose Yourself, Love Story, Let It Go, Livin' on a Prayer, Levitating, Lemon Tree, Layla, Locked Out of Heaven,
        Macarena, Mamma Mia, My Heart Will Go On, Mr. Brightside, Moves Like Jagger, Material Girl, My Way, Monster, Money, Memories, Moskau,
        No Woman No Cry, New York New York, Never Gonna Give You Up, Nothing Else Matters, Numb, Nine to Five, No Scrubs,
        One, Old Town Road, Oops!... I Did It Again, Over the Rainbow, One More Time, Only Girl, Ocean Eyes, Our Song,
        Perfect, Poker Face, Party in the USA, Purple Rain, Piano Man, Paradise, Pumped Up Kicks, Paparazzi, Positions, Photograph, Paint It Black,
        Queen of Kings,
        Rolling in the Deep, Respect, Roar, Royals, Rocket Man, Rehab, Radioactive, Ring of Fire, Rock You Like a Hurricane, Roxanne, Run the World, Riptide,
        Smells Like Teen Spirit, Shake It Off, Someone Like You, Sweet Child O' Mine, Single Ladies, Seven Nation Army, Stay, Shape of You, Shallow, Sorry, Sunflower, Stairway to Heaven, Summer of '69, Stand by Me, Super Bass, Sweet Home Alabama, September, Smooth Criminal, Symphony, Survivor, Sledgehammer, Starboy, Still D.R.E., Sweet Dreams, Stayin' Alive,
        Thriller, Toxic, The Scientist, Thinking Out Loud, Take on Me, Total Eclipse of the Heart, Thunderstruck, Titanium, The Sound of Silence, Teenage Dream, Tik Tok, Tiny Dancer, Truth Hurts, Time After Time, The Winner Takes It All, Torn,
        Umbrella, Uptown Funk, Under Pressure, Unholy, Under the Bridge, Uptown Girl, Use Somebody, Unwritten,
        Viva La Vida, Vogue, Video Games, Valerie, Vampires,
        Wonderwall, Wannabe, We Will Rock You, What a Wonderful World, Wrecking Ball, Watermelon Sugar, We Are the Champions, Wake Me Up, Without Me, What Is Love, Wind of Change, With or Without You, Walking on Sunshine, We Found Love, Whatcha Say, Where Is the Love?, Who Let the Dogs Out, White Christmas, Wildest Dreams, Work, Waka Waka,
        Xanadu, Xgon' Give It to Ya, XO,
        Yesterday, Yellow, YMCA, You Belong with Me, Your Song, You're the One That I Want, Yeah!, You Raise Me Up, Young and Beautiful,
        Zombie
        """,
        
        // MARK: - Alltag & Zuhause
        "Bis zu welchem Buchstaben kommst du bei Dingen im Badezimmer?": """
        Abfluss, Augencreme, Abschminktuch, Aftershave,
        Badewanne, Badeente, Badezimmerteppich, Bartschneider, Bürste, Bimsstein, Bodylotion, Bademantel, Badesalz, Becher,
        Creme, Conditioner, Curler,
        Deo, Duschgel, Duschvorhang, Duschkopf, Dusche, Dose,
        Eyeliner, Einwegrasierer, Eimer,
        Föhn, Fliesen, Feuchtigkeitscreme, Fußmatte, Fenster,
        Gesichtsmaske, Gel, Glätteisen, Glas,
        Handtuch, Handtuchhalter, Haarspray, Haargummi, Haarbürste, Heizung, Hygieneartikel, Haarspülung, Handseife, Haartrockner,
        Ingwer-Shampoo,
        Jalousie,
        Kamm, Klopapier, Klobürste, Kosmetiktücher, Kajal, Klinge, Kacheln, Kosmetikspiegel, Kondome,
        Lippenstift, Lockenwickler, Lappen, Lippenbalsam, Lampe, Lotion,
        Make-up, Mascara, Mundwasser, Matte, Medikamente, Mülleimer,
        Nagellack, Nagelschere, Nagelfeile, Nassrasierer, Nachtcreme,
        Öl, Ohrenstäbchen,
        Parfum, Puder, Pinzette, Peeling, Pflaster, Putzmittel, Pinsel, Papierkorb,
        Q-Tips,
        Rasierer, Rasierschaum, Rasierklinge, Regal, Reinigungsmilch,
        Seife, Shampoo, Spiegel, Schwamm, Schminke, Schere, Spülung, Steckdose, Stöpsel, Schrank, Slipeinlage, Sonnencreme, Schaumbad,
        Toilette, Toilettenpapier, Toilettenbürste, Topf, Tampon, Taschentücher, Teppich, Trockner,
        Uhr, Unterschrank,
        Ventilator, Vorhang, Vaseline,
        Waschbecken, Waschmaschine, Waschlappen, Wasserhahn, Wattepads, Wattestäbchen, WC, WC-Ente, Wickeltisch, Wimperntusche, Waage, Wäschekorb,
        Zahnbürste, Zahnpasta, Zahnseide, Zahnputzbecher, Zange
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Dingen in der Küche?": """
        Alufolie, Auflaufform, Arbeitsplatte, Abzugshaube, Abtropfsieb, Apfelschäler,
        Backofen, Besteck, Brettchen, Brotkasten, Backpapier, Becher, Butterdose, Besen, Backblech, Brotmesser,
        Dosenöffner, Dunstabzugshaube, Dampfgarer, Dose,
        Eierbecher, Eierkocher, Eimer, Espressokocher, Eisschrank, Esstisch, Eieruhr,
        Flaschenöffner, Fleischklopfer, Frischhaltefolie, Form, Feuerzeug, Filter, Fritteuse,
        Gabel, Geschirrspüler, Glas, Gefrierschrank, Gewürzregal, Grill, Geschirrtuch,
        Herd, Handtuch, Holzloffel, Hobel, Herdplatte, Haushaltsrolle, Handmixer,
        Induktionsherd,
        Kaffeemaschine, Kühlschrank, Kelle, Kochlöffel, Kochtopf, Kuchengabel, Kartoffelstampfer, Kanne, Korkenzieher, Küchenwaage, Küchenrolle, Knoblauchpresse, Karaffe, Käsereibe,
        Löffel, Lappen,
        Messer, Mikrowelle, Mixer, Messbecher, Mülleimer, Mörser, Muffinform, Mixstab,
        Nudelholz, Nussknacker, Nudelsieb,
        Ofen, Obstschale, Ofenhandschuh, Öffner, Ölflasche,
        Pfanne, Pfannenwender, Pürierstab, Pfeffermühle, Pizza-Schneider, Pinsel, Papiertücher,
        Quirl,
        Reibe, Reiskocher, Rührschüssel, Rollholz, Regal,
        Schere, Schüssel, Sieb, Spülmaschine, Spüle, Schwamm, Schneebesen, Schneidebrett, Salzstreuer, Sparschäler, Schöpfkelle, Spülmittel, Serviette, Strohhalm, Stuhl, Sandwichmaker,
        Teller, Tasse, Topf, Toaster, Teekanne, Thermoskanne, Tortenheber, Tisch, Topflappen, Tiefkühlfach, Tablett, Teelöffel, Trichter, Tupperware,
        Untertasse, Uhr,
        Vorratsdose,
        Waage, Wasserkocher, Wok, Weinglas, Waffeleisen, Wasserhahn, Wetzstahl,
        Zange, Zitronenpresse, Zuckerdose
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Haushaltsgeräten?": """
        Akkuschrauber, Alexa, Abzugshaube,
        Bügeleisen, Backofen, Bohrmaschine, Blu-ray-Player, Beamer, Brotbackautomat,
        Computer, Ceranfeld, Crepes-Maker,
        Dampfreiniger, Drucker, Dunstabzugshaube, Dörrgerät, DVD-Player,
        Eierkocher, Eismaschine, Entsafter, Epilierer, Elektroherd, Espressomaschine, Elektrische Zahnbürste,
        Fernseher, Föhn, Fritteuse, Fleischwolf, Faxgerät, Fensterreiniger, Fitness-Tracker, Ventilator,
        Gefrierschrank, Geschirrspüler, Grill, Glätteisen, Gameboy, Gasherd,
        Handy, Haartrockner, Heizlüfter, Herd, Handstaubsauger, Hi-Fi-Anlage, Headset, Heißluftfritteuse, Handmixer, Häcksler,
        Induktionsherd, iPad, iPhone, iPod,
        Kaffeemaschine, Kühlschrank, Klimaanlage, Küchenwaage, Kopfhörer, Kaffeemühle, Kopierer, Kamera, Konsole, Kochplatte, Kontaktgrill,
        Lampe, Laptop, Lautsprecher, Lockenstab, Luftbefeuchter, Luftreiniger, Ladegerät,
        Mikrowelle, Mixer, Monitor, Maus, Milchaufschäumer, Mähroboter,
        Nähmaschine, Nintendo, Notebook, Navigationsgerät, Nachttischlampe,
        Ofen,
        Playstation, PC, Pürierstab, Plattenspieler, Powerbank, Projektor, Pizzaofen,
        Raclette-Grill, Radio, Rasierer, Reiskocher, Router, Rauchmelder, Roboterstaubsauger, Receiver,
        Staubsauger, Spülmaschine, Smart Home, Smartwatch, Sandwichmaker, Smartphone, Stereoanlage, Saugroboter, Scanner, Stabmixer, Spielekonsole, Solarium, Standmixer,
        Toaster, Tablet, Telefon, Trockner, Tastatur, Thermomix, Taschenlampe, Teemaschine, TV, Tischgrill,
        Uhr, Ultraschallreiniger,
        Ventilator, Vakuumierer, Verstärker, Video-Rekorder,
        Waschmaschine, Wasserkocher, Wecker, Wäschetrockner, Waffeleisen, WLAN-Router, Waage, Webcam, Winkelschleifer, Walkie-Talkie,
        Xbox,
        Zahnbürste (elektrisch), Zeitschaltuhr
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Möbeln?": """
        Anrichte, Aktenschrank, Armlehne, Apothekerschrank,
        Bett, Bank, Beistelltisch, Bürostuhl, Bücherregal, Barhocker, Boxspringbett, Babybett, Bauernschrank,
        Couch, Couchtisch, Computertisch, Chesterfield-Sofa, Chaiselongue,
        Doppelbett, Drehstuhl, Dielenschrank, Daybed,
        Eckbank, Esstisch, Etagenbett, Eckschrank, Einbauküche,
        Fernsehsessel, Futon, Fernsehtisch, Flurgarderobe, Freischwinger,
        Garderobe, Glastisch, Gartenstuhl, Gartenliege, Gitterbett,
        Hocker, Hochbett, Hängematte, Hängesessel, Hochschrank, Himmelbett, Hollywoodschaukel,
        Inselküche,
        Jugendbett,
        Kleiderschrank, Kommode, Kinderbett, Küchenschrank, Klavierhocker, Klappstuhl, Klapptisch, Kaminofen, Küchenzeile,
        Lampe, Liege, Lattenrost, Laufstall, Lesesessel, Lowboard, Ledersofa,
        Matratze, Massagesessel, Murphy-Bett, Medizinschrank,
        Nachttisch, Nachtschrank, Nierentisch,
        Ohrensessel, Ottoman, Ofenbank,
        Polstermöbel, Paravent, Podest, Palettenmöbel, Pflanzenhocker,
        Regal, Relaxsessel, Récamiere, Rundtisch, Rattansessel, Raumteiler, Rollcontainer,
        Schrank, Stuhl, Sofa, Sessel, Schreibtisch, Schuhschrank, Sideboard, Schminktisch, Sekretär, Sitzsack, Spiegelschrank, Spiegel, Stehlampe, Schlafsofa, Servierwagen, Schemel, Schaukelstuhl,
        Tisch, Truhe, Teppich, Toilette, TV-Board, Theke, Tresen,
        Unterschrank,
        Vitrine, Vorhang,
        Wandregal, Wickelkommode, Wohnwand, Waschtisch, Wasserbett, Wäscheschrank, Werkbank, Wippe, Wiege, Weinschrank,
        Zeitungsständer
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Putzmitteln?": """
        Allzweckreiniger, Abflussreiniger, Antikalk, Alkoholreiniger,
        Badreiniger, Backofenspray, Bleichmittel, Bodenreiniger, Bürste, Besen, Bodentuch, Bimsstein,
        Chlorreiniger, Ceranfeldreiniger, Cillit Bang, Chrompolitur,
        Desinfektionsmittel, Domestos, Duster, Drahtbürste, Dampfreiniger,
        Essigreiniger, Eimer, Entkalker, Edelstahlreiniger,
        Fensterreiniger, Fleckentferner, Fettlöser, Feuchttücher, Fugenreiniger, Fliesenreiniger, Feinwaschmittel,
        Glasreiniger, Geschirrspülmittel, General, Gummihandschuhe, Glaskeramikreiniger, Grillreiniger, Gallseife,
        Handfeger, Handschuhe, Haushaltsreiniger, Hygienespüler, Holzpolitur, Handseife,
        Insektenspray, Imprägnierspray,
        Javelwasser,
        Kalkreiniger, Klarspüler, Klostein, Küchenreiniger, Kehrblech, Kernseife, Kunststoffreiniger, Kratzschwamm,
        Lappen, Lederpflege, Luftverbesserer, Laminatreiniger,
        Möbelpolitur, Meister Proper, Metallpolitur, Mopp, Müllbeutel, Mikrofasertuch, Maschinenreiniger,
        Natron, Neutralreiniger, Nasssauger,
        Orangenreiniger,
        Putzlappen, Putzstein, Polierspray, Parkettpflege, Plastikreiniger, Papiertücher,
        Quast,
        Rohrreiniger, Reinigungsalkohol, Rostlöser, Reinigungsmilch,
        Scheuermilch, Schwamm, Spülmittel, Seife, Sanitärreiniger, Schimmelentferner, Staubsauger, Stahlwolle, Salz (Spülmaschine), Soda, Schuhcreme, Staubwedel, Sprühflasche, Schmierseife, Silberbad,
        Teppichreiniger, Toilettenreiniger, Tuch, Terpentin, Textilerfrischer,
        Universalreiniger, Urinsteinlöser,
        Vanish, Vorwaschspray, Vollwaschmittel,
        Waschmittel, Weichspüler, Wischmopp, WC-Reiniger, Wunderschwamm, Wachs, Wasser, Wischtuch, Waschsoda, Wollwaschmittel,
        Zitronensäure, Zahnpasta (Hausmittel)
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Dingen, die man in der Schule findet?": """
        Atlas, Aula, Anspitzer, Aufgabenheft, Arbeitsblatt,
        Buch, Bleistift, Block, Buntstift, Brotdose, Bücherei, Beamer, Bank, Bibliothek, Biologieraum,
        Computer, Computerraum, Chemie-Labor, Collegeblock,
        Dreieck (Geodreieck), Direktor, Drucker,
        Etui, Englischbuch,
        Füller, Filzstift, Federmäppchen, Fenster, Ferien, Folie, Fotokopierer, Fibel, Farben,
        Geodreieck, Globus, Garderobe, Gummiband, Geschichte-Buch, Geographie-Buch,
        Heft, Hausaufgaben, Hausmeister, Handy (verboten), Hof, Hausaufgabenheft, Hausschuhe,
        iPad, Informatikraum, Inbus,
        Jausenbox, Jacke,
        Klassenzimmer, Kreide, Kugelschreiber, Kleber, Klebestift, Karte, Klassenbuch, Kopierer, Kuli, Kalender, Kiosk, Kunstraum,
        Lineal, Lehrer, Lehrbuch, Lehrerzimmer, Locher, Landkarte, Laptop, Leinwand,
        Mäppchen, Mathebuch, Musikraum, Mensa, Mülleimer, Mitschüler, Markierer, Malkasten, Magnet, Mikroskop,
        Notizblock, Noten, Namensschild, Ordner, Overheadprojektor,
        Pause, Pausenhof, Papier, Pinsel, Pausenbrot, Projektor, Pinnwand, Plakat, Physikraum, Pult, Papierkorb, Patrone,
        Quader,
        Ranzen, Radiergummi, Rechner, Rucksack, Register, Regal, Ringbuch, Rektor,
        Schere, Stift, Stuhl, Schwamm, Schule, Schüler, Schultasche, Spitzer, Stundenplan, Sportbeutel, Sporthalle, Smartboard, Sekretariat, Schulhof, Schulbus, Schließfach, Schreibblock,
        Tafel, Tisch, Tintenkiller, Turnhalle, Tasche, Taschenrechner, Tacker, Textmarker, Tintenpatrone, Tablet, Toiletten, Turnbeutel, Tuschkasten,
        Unterricht, Umschlag, Uhr,
        Vertretungsplan, Vokabelheft,
        Whiteboard, Wörterbuch, Wasserfarben, Winkelmesser, Wandkarte, Werkraum,
        Zeugnis, Zirkel, Zeichenblock, Zettel
        """,
        
        // MARK: - Technik & Online
        "Bis zu welchem Buchstaben kommst du bei Apps?": """
        Amazon, Airbnb, Asana, Audible, Adobe, Apple Music,
        Booking.com, Bumble, BeReal, Babbel, Bitmoji, Bolt, Bring!,
        Candy Crush, ChatGPT, Chrome, Canva, Calm, Clash of Clans, Calendar, Calculator, CapCut, Coursera,
        Dropbox, Discord, Duolingo, Disney+, Deezer, DB Navigator, Lieferando, DAZN, Docs,
        eBay, Excel, Etsy, Evernote, ESPN, Email, Edge,
        Facebook, FaceTime, Firefox, Fitbit, Flo, Free Now, Flink, Facetune,
        Google, Google Maps, Gmail, Grindr, Goodreads, Gorillas, Groupon, GarageBand, GitHub,
        Hinge, Headspace, Hulu, HBO Max, Health,
        Instagram, IMDb, iTunes, Immoscout, IKEA,
        Jodel, Just Eat,
        Kindle, Komoot, Klarna, Kwai, Kahoot,
        LinkedIn, Lieferando, Lightroom, Line, Lyft, Lensa,
        Messenger, Maps, Musik, McDonalds, Microsoft Teams, MyFitnessPal, Mail, Minecraft, Meet,
        Netflix, Notes (Notizen), Nike, Notion, N26,
        Outlook, OneDrive, OpenTable, Opera,
        Pinterest, PayPal, Photoshop, Pokemon Go, Prime Video, PicsArt, Podigee, Podcasts, Procreate,
        Quizduell, QR Code Reader, Quora,
        Reddit, Roblox, Revolut, Runtastic, Ryanair, Readdle,
        Spotify, Snapchat, Safari, Shazam, Slack, Skype, Signal, Strava, Soundcloud, Shein, StepStone, Stocard, Subway Surfers,
        TikTok, Twitter (X), Telegram, Tinder, Twitch, Teams, Translate, Trello, Tumblr, Too Good To Go, Taxfix, TripAdvisor, Temu,
        Uber, Uber Eats, Udemy, Unsplash,
        Vinted, VLC, Viber, VSCO, Venmo, VPN,
        WhatsApp, Waze, Word, Weather, Wikipedia, Wish, Wallet, WeTransfer, Wolt,
        X (Twitter), Xing, Xbox,
        YouTube, Yelp, Yahoo Mail, Yazio, YouTube Music,
        Zoom, Zalando, Zara, Zenly
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Social-Media-Plattformen?": """
        Ask.fm, Amino,
        BeReal, Badoo, Bluesky,
        Clubhouse, CraigsList,
        Discord, DeviantArt, Douyin,
        Facebook, Flickr, Foursquare,
        Gab, Goodreads, Grindr,
        Houseparty, Hinge,
        Instagram, ICQ, Imgur,
        Jodel,
        Kik, Knuddels,
        LinkedIn, Line, Likee, Last.fm, Letterboxd,
        Myspace, Messenger, Mastodon, Meetup, MeWe,
        Nextdoor,
        OkCupid, OnlyFans, Orkut,
        Pinterest, Parler, Periscope, Pluddemann,
        Quora, Qzone,
        Reddit, Rumble, ResearchGate,
        Snapchat, Skype, Slack, Signal, Soundcloud, Steam, StayFriends, SlideShare, StudiVZ, Strava,
        TikTok, Twitter, Telegram, Tumblr, Tinder, Twitch, Threads, Truth Social, Triller, Teams,
        Viber, VKontakte, Vimeo, Vine, Vero,
        WhatsApp, WeChat, Weibo, Wattpad, Wer-kennt-wen, Xing,
        X (Twitter), Xing,
        YouTube, Yubo, Yelp, Yammer,
        Zoom
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Handy-Herstellern?": """
        Alcatel, Apple, Asus, Acer, Archos, Amazon (Fire Phone),
        BlackBerry, BenQ, Blu,
        Cat, Coolpad, Cubot,
        Dell, Doogee, Doro,
        Ericsson, Essential,
        Fairphone, Fujitsu,
        Google (Pixel), Gigaset, Garmin,
        Honor, HTC, Huawei, HP, Hisense, HMD Global,
        Infinix, Itel,
        Jolla,
        Kyocera, Kodak,
        Lenovo, LG, LeEco, Lava,
        Motorola, Microsoft, Meizu, Micromax, Marshall, Mobistel, Medion,
        Nokia, Nothing, Nubia, OnePlus, Nec, Neffos,
        Oppo, Oukitel,
        Panasonic, Palm, Philips, Poco, Prestigio,
        QMobile,
        Realme, Razer, RIM, RED,
        Samsung, Sony, Sharp, Siemens, Shift, Sonim,
        TCL, Tecno, TP-Link, Toshiba, T-Mobile,
        Ulefone, Umidigi,
        Vivo, Vertu, Vodafone, ViewSonic,
        Wiko, Windows Phone, OnePlus, Xiaomi,
        Xperia (Sony), Xiaomi,
        Yota,
        ZTE, Zopo
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Gaming-Konsolen?": """
        Atari 2600, Atari Jaguar, Atari Lynx, Amiga CD32, Arcade,
        ColecoVision, Commodore 64,
        Dreamcast, DS (Nintendo), DSi,
        Game Boy, Game Boy Color, Game Boy Advance, GameCube, Game Gear, Genesis, Game & Watch,
        Intellivision,
        Jaguar,
        Magnavox Odyssey, Master System, Mega Drive,
        NES (Nintendo Entertainment System), Neo Geo, Nintendo 64, Nintendo DS, Nintendo Switch, Nintendo 3DS, N-Gage,
        Ouya, Oculus Quest,
        PlayStation 1, PlayStation 2, PlayStation 3, PlayStation 4, PlayStation 5, PSP, PS Vita, PS VR, PC Engine, Panasonic 3DO, Philips CD-i,
        Quest (Meta),
        Saturn (Sega), Sega Genesis, Sega Mega Drive, Sega Dreamcast, Super Nintendo (SNES), Switch, Steam Deck, Stadia, Sega Nomad,
        TurboGrafx-16,
        Virtual Boy, Vectrex, Valve Index,
        Wii, Wii U, WonderSwan,
        Xbox, Xbox 360, Xbox One, Xbox Series X, Xbox Series S,
        Zeebo, ZX Spectrum
        """,
        
        "Bis zu welchem Buchstaben kommst du bei Streaming-Diensten?": """
        Amazon Prime Video, Apple TV+, ARD Mediathek, Arte, Anime on Demand, Audible,
        Crunchyroll, Canal+, CuriosityStream, Crackle,
        Disney+, DAZN, Deezer, Discovery+, Dailymotion,
        ESPN+, Eurosport Player,
        FuboTV, Funimation, Freevee, Filmmit,
        Google Play Movies, Globoplay,
        Hulu, HBO Max, Hayu, Hoichoi,
        iQIYI, iTunes, IMDb TV,
        Joyn, JioCinema,
        Kodi, Kanopy,
        Lionsgate+, Looke,
        MUBI, MagentaTV, Max, Mixcloud, MyCanal,
        Netflix, Now TV, NFL Game Pass, NBA League Pass, Nebula, Napster,
        Paramount+, Peacock, Plex, Pluto TV, Philo, Prime Video, PlayStation Video,
        Qello,
        Rakuten TV, Roku Channel, RTL+, Red Bull TV,
        Spotify, Sky Show, Sky Ticket, Sky Go, SoundCloud, Starz, Shudder, Sling TV, Sony Liv, Shahid, Samsung TV Plus,
        Tidal, Tubi, Twitch, TVNow, Tennis Channel, TikTok, Tencent Video, The Roku Channel, TuneIn,
        Vimeo, Viki, Viaplay, Vudu, Vevo, Videoload, VRV,
        Wow (Sky), Waipu.tv, Wakanim, WeTV, WWE Network,
        YouTube, YouTube Premium, YouTube Music, YuppTV, Youku,
        ZDF Mediathek, Zattoo, Zee5
        """,
        
        // MARK: - Sport & Fitness
        "Bis zu welchem Buchstaben kommst du bei Fußballvereinen?": """
        Arsenal, Ajax Amsterdam, AC Mailand, Atletico Madrid, Aston Villa, AS Rom, Atalanta Bergamo, Anderlecht, Al-Nassr, Augsburg, Alemannia Aachen,
        Bayern München, Barcelona, Borussia Dortmund, Bayer Leverkusen, Benfica Lissabon, Boca Juniors, Besiktas Istanbul, Borussia Mönchengladbach, Bochum, Bremen, Brighton, Brentford, Burnley, Basel,
        Chelsea, Celtic Glasgow, Club Brügge, Chicago Fire, Crystal Palace, Corinthians, Cottbus, Chemnitz, Cadiz, Celta Vigo,
        Dynamo Dresden, Dynamo Kiew, Duisburg, Darmstadt 98, Derby County, Deportivo La Coruna,
        Eintracht Frankfurt, Everton, Eindhoven (PSV), Espanyol Barcelona, Elche, Erzgebirge Aue, Energie Cottbus,
        Fenerbahce, Feyenoord Rotterdam, Fulham, Freiburg, Fortuna Düsseldorf, Fiorentina (Florenz), Flamengo, Frankfurt, FC Köln, FC St. Pauli,
        Galatasaray, Greuther Fürth, Genua, Getafe, Gladbach, Girona, Gremio, Glasgow Rangers,
        Hamburger SV, Hannover 96, Hertha BSC, Hoffenheim, Hansa Rostock, Heidenheim, Holstein Kiel, Hull City, Hajduk Split,
        Inter Mailand, Inter Miami, Ingolstadt, Ipswich Town, Independiente,
        Juventus Turin, Jahn Regensburg, Jena,
        Kaiserslautern, Karlsruher SC, Köln, Kopenhagen, Kiel, Kickers Offenbach,
        Liverpool, Lazio Rom, Leipzig (RB), Leverkusen, Leicester City, Leeds United, Lyon, Lille, Los Angeles Galaxy, Lens, Luton Town,
        Manchester United, Manchester City, Milan, Madrid (Real/Atletico), Marseille, Monaco, Mönchengladbach, Mainz 05, Mallorca, Magdeburg, Meppen, 1860 München,
        Napoli (Neapel), Newcastle United, Nürnberg, Nottingham Forest, Nantes, Nice (Nizza), New York Red Bulls, Norwich City,
        Olympique Lyon, Olympique Marseille, Osasuna, Orlando City, Olympiakos Piräus, Osnabrück, Oldenburg,
        Paris Saint-Germain (PSG), Porto, PSV Eindhoven, Palmeiras, Panathinaikos, Parma, Paderborn, Preußen Münster,
        Queens Park Rangers,
        Real Madrid, RB Leipzig, Roma, River Plate, Rangers, Rapid Wien, Real Sociedad, Rayo Vallecano, Rennes, Rostock, Regensburg, Rot-Weiss Essen,
        Schalke 04, Sevilla, Sporting Lissabon, Southampton, Stuttgart, St. Pauli, Salzburg, Sao Paulo, Sheffield United, Swansea, Sunderland, Sandhausen, Saarbrücken, Stoke City,
        Tottenham Hotspur, Turin (Juventus/Torino), Trabzonspor, Twente Enschede, Toronto FC, Toulouse,
        Union Berlin, Udinese Calcio, Unterhaching, Ulm,
        Valencia, Villarreal, VfB Stuttgart, VfL Wolfsburg, VfL Bochum, Vasco da Gama, Vitesse Arnheim, Verona, Venedig, Viktoria Köln,
        Werder Bremen, West Ham United, Wolfsburg, Watford, Wolverhampton Wanderers, West Bromwich Albion, Wehen Wiesbaden, Würzburger Kickers,
        Xamax (Neuchâtel),
        Young Boys Bern,
        Zenit St. Petersburg, Zürich, Zwickau
        """,

    ]
}
