import Foundation

struct ClassicHints {
    static let data: [String: String] = [
        // --- Geografie & Orte ---
        "Wie viele Städte in Italien kann dein Partner aufzählen?": "Rom,Mailand,Venedig,Neapel,Florenz,Turin,Palermo,Genua,Verona,Bologna,Pisa",
        "Wie viele Flüsse kennt dein Partner?": "Rhein,Donau,Nil,Amazonas,Elbe,Weser,Mosel,Themse,Mississippi,Wolga,Seine",
        "Wie viele Gebirge kann dein Partner aufzählen?": "Alpen,Himalaya,Rocky Mountains,Anden,Pyrenäen,Ural,Atlas,Kaukasus,Karpaten,Appalachen",
        "Wie viele Länder mit A am Anfang kennt dein Partner?": "Argentinien,Australien,Ägypten,Albanien,Algerien,Afghanistan,Angola,Armenien,Aserbaidschan,Äthiopien",
        "Wie viele Länder, deren Name mit K beginnt, kann dein Partner aufzählen?": "Kanada,Kroatien,Kolumbien,Kenia,Kuba,Katar,Kambodscha,Kamerun,Kasachstan,Kuwait",
        "Wie viele Städte, deren Name mit M beginnt, kann dein Partner aufzählen?": "München,Madrid,Mailand,Moskau,Manchester,Miami,Montreal,Melbourne,Marseille,Manila",
        "Wie viele Städte, deren Name auf \"burg\" endet, kennt dein Partner?": "Hamburg,Sankt Petersburg,Straßburg,Salzburg,Freiburg,Augsburg,Würzburg,Duisburg,Regensburg,Johannesburg",
        "Wie viele Länder ohne Küste kennt dein Partner?": "Schweiz,Österreich,Ungarn,Tschechien,Serbien,Slowakei,Bolivien,Paraguay,Luxemburg,Liechtenstein",
        "Wie viele Städte in Spanien kann dein Partner aufzählen?": "Madrid,Barcelona,Valencia,Sevilla,Malaga,Bilbao,Granada,Palma,Alicante",
        "Wie viele Länder in Afrika kann dein Partner aufzählen?": "Südafrika,Ägypten,Marokko,Nigeria,Kenia,Ghana,Tunesien,Äthiopien,Senegal,Kamerun",
        "Wie viele Flughäfen kann dein Partner nennen?": "Frankfurt,München,Berlin (BER),London Heathrow,Paris CDG,Dubai,JFK New York,Los Angeles (LAX),Amsterdam",
        "Wie viele Berge über 4000m kennt dein Partner?": "Mount Everest,K2,Mont Blanc,Matterhorn,Kilimandscharo,Dufourspitze,Elbrus",
        "Wie viele europäische Hauptstädte kann dein Partner aufzählen?": "Berlin,Paris,London,Rom,Madrid,Wien,Bern,Brüssel,Amsterdam,Lissabon,Athen,Prag",
        "Wie viele Flüsse in Deutschland kann dein Partner nennen?": "Rhein,Elbe,Donau,Main,Weser,Mosel,Spree,Neckar,Oder,Isar,Ruhr",
        "Wie viele Länder, deren Name mit L beginnt, kennt dein Partner?": "Luxemburg,Lettland,Litauen,Libanon,Libyen,Liechtenstein,Laos,Liberia",
        "Wie viele Strände oder Inseln fallen deinem Partner ein?": "Mallorca,Sylt,Rügen,Hawaii,Bali,Ibiza,Kreta,Sardinien,Sizilien,Malediven,Bora Bora",
        "Wie viele Inselstaaten kennt dein Partner?": "Japan,Großbritannien,Island,Neuseeland,Kuba,Madagaskar,Philippinen,Indonesien,Zypern,Malta",
        "Wie viele US-Bundesstaaten kann dein Partner nennen?": "Kalifornien,Texas,Florida,New York,Hawaii,Alaska,Nevada,Washington,Ohio,Arizona",
        "Wie viele Naturparks oder Nationalparks kennt dein Partner?": "Yellowstone,Grand Canyon,Yosemite,Krüger,Bayerischer Wald,Schwarzwald,Serengeti",
        "Wie viele Länder, deren Name mit \"S\" beginnt, kennt dein Partner?": "Spanien,Schweiz,Schweden,Serbien,Slowakei,Slowenien,Somalia,Sudan,Syrien,Senegal",
        "Wie viele Länder mit mehr als einer Amtssprache kennt dein Partner?": "Schweiz,Belgien,Kanada,Südafrika,Indien,Finnland,Singapur,Luxemburg",
        "Wie viele Länder mit Euro als Währung kann dein Partner nennen?": "Deutschland,Frankreich,Italien,Spanien,Österreich,Niederlande,Belgien,Griechenland,Portugal,Irland",

        // --- Marken & Produkte ---
        "Wie viele Handy-Anbieter kann dein Partner nennen?": "Telekom,Vodafone,O2,1&1,Congstar,Blau,Aldi Talk,Otelo,Freenet",
        "Wie viele Marken von Mineralwasser kann dein Partner nennen?": "Gerolsteiner,Volvic,Vittel,Evian,San Pellegrino,Apollinaris,Vöslauer,Adelholzener,Black Forest",
        "Wie viele Getränkemarken kann dein Partner aufzählen?": "Coca-Cola,Pepsi,Fanta,Sprite,Red Bull,Lipton,Schweppes,Monster,Mezzo Mix,7Up",
        "Wie viele große Modedesigner kann dein Partner nennen?": "Karl Lagerfeld,Gucci,Versace,Chanel,Armani,Dior,Tommy Hilfiger,Calvin Klein,Prada,Yves Saint Laurent",
        "Wie viele Supermarktketten kennt dein Partner?": "Aldi,Lidl,Rewe,Edeka,Kaufland,Penny,Netto,Globus,Tegut,Norma",
        "Wie viele Mode-Marken kennt dein Partner?": "Nike,Adidas,Zara,H&M,Gucci,Prada,Louis Vuitton,Hermès,Uniqlo,Puma",
        "Wie viele Automarken kann dein Partner nennen?": "VW,BMW,Mercedes,Audi,Toyota,Ford,Tesla,Porsche,Opel,Ferrari,Lamborghini",
        "Wie viele Marken von Sneakern kennt dein Partner?": "Nike Air Force,Jordan,Adidas Samba,Yeezy,Converse Chucks,Vans,New Balance,Asics,Reebok,Puma",
        "Wie viele Automodelle von Tesla kennt dein Partner?": "Model S,Model 3,Model X,Model Y,Cybertruck,Roadster",
        "Wie viele Marken von Kopfhörern kennt dein Partner?": "Sony,Bose,Apple (AirPods),Beats,Sennheiser,JBL,Marshall,Teufel,Audio-Technica",
        "Wie viele Fahrzeuge mit Elektroantrieb kann dein Partner aufzählen?": "Tesla,VW ID.3,Porsche Taycan,Renault Zoe,Audi e-tron,BMW i3,Hyundai Ioniq,Polestar",
        "Wie viele Automarken aus Japan kann dein Partner nennen?": "Toyota,Honda,Nissan,Mazda,Suzuki,Mitsubishi,Subaru,Lexus",
        "Wie viele Automarken mit B am Anfang kennt dein Partner?": "BMW,Bentley,Bugatti,Brabus,BYD,Borgward,Buick",
        "Wie viele Uhrenmarken kennt dein Partner?": "Rolex,Omega,Swatch,Casio,Breitling,Patek Philippe,Seiko,Tag Heuer,Hublot,Fossil",
        "Wie viele Marken von Schokolade kann dein Partner aufzählen?": "Milka,Lindt,Ritter Sport,Kinder,Toblerone,Ferrero,Mars,Snickers,Merci",
        "Wie viele Automodelle mit Elektroantrieb fallen deinem Partner ein?": "Model 3,Model Y,ID.3,ID.4,Taycan,Zoe,e-tron,Ioniq 5,Leaf",
        "Wie viele Automarken aus Deutschland kennt dein Partner?": "Volkswagen,Mercedes-Benz,BMW,Audi,Porsche,Opel,Smart",
        "Wie viele Energydrink-Marken kann dein Partner aufzählen?": "Red Bull,Monster,Rockstar,Effect,28 Black,Bullit,Relentless,Booster",
        "Wie viele Süßigkeiten-Marken fallen deinem Partner ein?": "Haribo,Kinder,Milka,Snickers,Twix,M&Ms,Katjes,Trolli,KitKat",
        "Wie viele Automarken, deren Name mit M beginnt, kennt dein Partner?": "Mercedes,Mazda,Mitsubishi,Mini,Maserati,McLaren,Maybach,MAN",

        // --- Popkultur & Medien ---
        "Wie viele Computerspiele kennt dein Partner?": "Minecraft,Fortnite,FIFA (EA FC),Call of Duty,GTA,Super Mario,League of Legends,Sims,Zelda,Pokemon",
        "Wie viele Oper oder Theaterstücke kennt dein Partner?": "Zauberflöte,Carmen,Faust,Romeo und Julia,Hamlet,Aida,Phantom der Oper,Macbeth,La Traviata",
        "Wie viele bekannte Twitch-Streamer kennt dein Partner?": "MontanaBlack,Knossi,Papaplatte,Trymacs,EliasN97,Ninja,Shroud,Pokimane,Gronkh",
        "Wie viele Disney-Filme kann dein Partner nennen?": "König der Löwen,Die Eiskönigin,Aladdin,Arielle,Mulan,Vaiana,Encanto,Schneewittchen,Cinderella",
        "Wie viele Superhelden aus Filmen kann dein Partner nennen?": "Batman,Superman,Spider-Man,Iron Man,Wonder Woman,Thor,Hulk,Captain America,Black Widow",
        "Wie viele Schauspieler kennt dein Partner?": "Leonardo DiCaprio,Brad Pitt,Tom Cruise,Johnny Depp,Dwayne Johnson,Tom Hanks,Matthias Schweighöfer",
        "Wie viele Schauspieler aus Hollywood kann dein Partner nennen?": "Angelina Jolie,Julia Roberts,Meryl Streep,Jennifer Lawrence,Scarlett Johansson,Will Smith,Ryan Reynolds",
        "Wie viele Songs von Michael Jackson kann dein Partner aufzählen?": "Thriller,Billie Jean,Beat It,Bad,Smooth Criminal,Earth Song,Black or White,Man in the Mirror",
        "Wie viele Serien auf Netflix kann dein Partner spontan nennen?": "Stranger Things,Squid Game,Haus des Geldes,Wednesday,The Crown,Bridgerton,Dark,Black Mirror,The Witcher",
        "Wie viele Musicals kann dein Partner nennen?": "König der Löwen,Phantom der Oper,Mamma Mia,Aladdin,Tarzan,Wicked,Hamilton,Starlight Express,Tanz der Vampire",
        "Wie viele Videospiel-Charaktere kann dein Partner aufzählen?": "Mario,Luigi,Link,Pikachu,Sonic,Lara Croft,Kratos,Master Chief,Donkey Kong",
        "Wie viele Podcasts kann dein Partner nennen?": "Gemischtes Hack,Fest & Flauschig,Baywatch Berlin,Zeit Verbrechen,Lage der Nation,Hobbylos,Dick & Doof",
        "Wie viele Streaming-Dienste kann dein Partner aufzählen?": "Netflix,Amazon Prime,Disney+,Apple TV+,DAZN,Spotify,YouTube Premium,Paramount+",
        "Wie viele Planetennamen aus Sci-Fi kennt dein Partner?": "Tatooine,Vulcan,Arrakis (Dune),Krypton,Pandora (Avatar),Hoth,Gallifrey",
        "Wie viele Comedians kann dein Partner aufzählen?": "Mario Barth,Carolin Kebekus,Dieter Nuhr,Chris Tall,Felix Lobrecht,Kevin Hart,Dave Chappelle,Ricky Gervais",
        "Wie viele Rockbands kennt dein Partner?": "AC/DC,Queen,Rolling Stones,Metallica,Nirvana,Linkin Park,Guns N' Roses,Beatles,Pink Floyd",
        "Wie viele Disney-Prinzessinnen kann dein Partner aufzählen?": "Cinderella,Belle,Arielle,Jasmin,Rapunzel,Elsa,Anna,Schneewittchen,Pocahontas",
        "Wie viele YouTuber kann dein Partner aufzählen?": "PewDiePie,MrBeast,Rezo,BibisBeautyPalace,Unge,Gronkh,Julien Bam,Dagi Bee",
        "Wie viele Märchenfiguren kann dein Partner aufzählen?": "Rotkäppchen,Aschenputtel,Schneewittchen,Froschkönig,Dornröschen,Der böse Wolf,Hänsel & Gretel,Rumpelstilzchen",
        "Wie viele Fernsehserien aus den 90ern kennt dein Partner?": "Friends,Seinfeld,Simpsons,Akte X,Prinz von Bel-Air,Full House,Eine schrecklich nette Familie,Baywatch",
        "Wie viele Harry-Potter-Charaktere kann dein Partner aufzählen?": "Harry Potter,Ron Weasley,Hermine Granger,Dumbledore,Snape,Voldemort,Hagrid,Draco Malfoy,Sirius Black",
        "Wie viele Mittelalter-Filme oder -Serien kennt dein Partner?": "Game of Thrones,Braveheart,Gladiator,Herr der Ringe,Vikings,The Witcher,Königreich der Himmel",
        "Wie viele bekannte DJs kennt dein Partner?": "David Guetta,Avicii,Tiësto,Calvin Harris,Steve Aoki,Skrillex,Robin Schulz,Felix Jaehn,Martin Garrix",
        "Wie viele bekannte Podcasts aus Deutschland kann dein Partner nennen?": "Gemischtes Hack,Fest & Flauschig,Baywatch Berlin,Hobbylos,Zeit Verbrechen,Lage der Nation",

        // --- Sport & Spiele ---
        "Wie viele Sportarten, die olympisch sind, kann dein Partner aufzählen?": "Schwimmen,Leichtathletik,Turnen,Judo,Fechten,Fußball,Tennis,Basketball,Volleyball,Rudern",
        "Wie viele berühmte Boxer kann dein Partner nennen?": "Muhammad Ali,Mike Tyson,Floyd Mayweather,Klitschko,Manny Pacquiao,Tyson Fury,Anthony Joshua",
        "Wie viele Spiele, die man mit Karten spielt, kennt dein Partner?": "Poker,Skat,Mau-Mau,Uno,Black Jack,Rommé,Canasta,Solitaire,Durak",
        "Wie viele Sportarten, die man in der Halle spielt, fallen deinem Partner ein?": "Handball,Basketball,Volleyball,Futsal,Badminton,Turnen,Tischtennis,Hockey",
        "Wie viele Fußball-Weltmeister kann dein Partner aufzählen?": "Deutschland,Brasilien,Italien,Argentinien,Frankreich,Uruguay,England,Spanien",
        "Wie viele verschiedene Sportarten mit Schnee oder Eis kennt dein Partner?": "Ski Alpin,Biathlon,Eishockey,Skispringen,Bob,Eiskunstlauf,Snowboard,Langlauf,Curling",
        "Wie viele berühmte Sportlerinnen kennt dein Partner?": "Serena Williams,Steffi Graf,Angelique Kerber,Magdalena Neuner,Lindsey Vonn,Simone Biles,Naomi Osaka",
        "Wie viele Sportarten mit einem Netz kennt dein Partner?": "Volleyball,Tennis,Badminton,Tischtennis,Padel,Pickleball,Beachvolleyball",
        "Wie viele Brettspiele fallen deinem Partner ein?": "Monopoly,Mensch ärgere dich nicht,Siedler von Catan,Risiko,Schach,Scrabble,Cluedo,Spiel des Lebens",
        "Wie viele berühmte Fußballer kann dein Partner aufzählen?": "Messi,Ronaldo,Mbappé,Neymar,Thomas Müller,Manuel Neuer,Pele,Maradona,Zidane",
        "Wie viele Fußballtrainer fallen deinem Partner ein?": "Jürgen Klopp,Pep Guardiola,Mourinho,Thomas Tuchel,Nagelsmann,Ancelotti,Jogi Löw,Hansi Flick",
        "Wie viele E-Sport-Teams kennt dein Partner?": "G2 Esports,Fnatic,Cloud9,T1,SK Gaming,Team Liquid,FaZe Clan,BIG",
        "Wie viele Fußballstadien kann dein Partner nennen?": "Allianz Arena,Signal Iduna Park,Wembley,Camp Nou,Bernabéu,Old Trafford,Maracanã,Olympiastadion",
        "Wie viele bekannten Fußballschiedsrichter fallen deinem Partner ein?": "Pierluigi Collina,Markus Merk,Felix Brych,Deniz Aytekin,Howard Webb,Bibiana Steinhaus",
        "Wie viele Brettspiel-Klassiker vor 2000 kennt dein Partner?": "Schach,Mühle,Dame,Backgammon,Halma,Mensch ärgere dich nicht,Monopoly,Risiko,Scrabble",

        // --- Natur & Wissenschaft ---
        "Wie viele Tiere, die im Wasser leben, kann dein Partner nennen?": "Wal,Delfin,Hai,Qualle,Tintenfisch,Seepferdchen,Lachs,Forelle,Krebs,Rochen",
        "Wie viele Arten von Kuchen kann dein Partner nennen?": "Käsekuchen,Marmorkuchen,Apfelkuchen,Schwarzwälder Kirsch,Donauwelle,Sachertorte,Brownie",
        "Wie viele Baumarten kann dein Partner nennen?": "Eiche,Buche,Fichte,Kiefer,Ahorn,Birke,Linde,Kastanie,Tanne,Pappel",
        "Wie viele Tiere mit \"S\" kennt dein Partner?": "Schlange,Schaf,Schwein,Spinne,Schildkröte,Seehund,Skorpion,Spatz,Specht,Storch",
        "Wie viele Gemüsearten kann dein Partner aufzählen?": "Karotte,Tomate,Gurke,Paprika,Zwiebel,Kartoffel,Spinat,Brokkoli,Salat,Zucchini",
        "Wie viele Planeten oder Monde fallen deinem Partner ein?": "Erde,Mars,Venus,Jupiter,Saturn,Merkur,Neptun,Uranus,Mond (Erde),Titan,Europa",
        "Wie viele Gewürze kann dein Partner aufzählen?": "Salz,Pfeffer,Paprika,Curry,Zimt,Oregano,Basilikum,Muskat,Chili,Ingwer,Rosmarin",
        "Wie viele Arten von Pasta kann dein Partner nennen?": "Spaghetti,Penne,Fusilli,Tagliatelle,Farfalle,Lasagne,Ravioli,Makkaroni,Tortellini",
        "Wie viele Kräuter für Tee fallen deinem Partner ein?": "Pfefferminze,Kamille,Fenchel,Brennessel,Salbei,Melisse,Ingwer,Hagebutte",
        "Wie viele Wissenschaftler:innen kann dein Partner nennen?": "Albert Einstein,Isaac Newton,Charles Darwin,Marie Curie,Nikola Tesla,Stephen Hawking,Galileo Galilei",
        "Wie viele Eissorten kann dein Partner nennen?": "Vanille,Schoko,Erdbeer,Stracciatella,Pistazie,Mango,Zitrone,Haselnuss,Joghurt",
        "Wie viele Sternzeichen kennt dein Partner?": "Widder,Stier,Zwillinge,Krebs,Löwe,Jungfrau,Waage,Skorpion,Schütze,Steinbock,Wassermann,Fische",
        "Wie viele Holzarten kennt dein Partner?": "Eiche,Buche,Kiefer,Fichte,Ahorn,Nussbaum,Mahagoni,Teak,Birke",
        "Wie viele Meeresbewohner kann dein Partner aufzählen?": "Hai,Wal,Delfin,Oktopus,Qualle,Seestern,Krabbe,Clownfisch,Hummer",
        "Wie viele Käsesorten kann dein Partner aufzählen?": "Gouda,Emmentaler,Mozzarella,Parmesan,Camembert,Cheddar,Feta,Brie,Gorgonzola",
        "Wie viele Gemüsesorten, die grün sind, kann dein Partner aufzählen?": "Gurke,Zucchini,Brokkoli,Spinat,Erbsen,Bohnen,Salat,Avocado,Lauch",
        "Wie viele Halbedelsteine oder Edelsteine kennt dein Partner?": "Diamant,Rubin,Saphir,Smaragd,Amethyst,Topas,Opal,Bernstein,Jade",
        "Wie viele Chemie-Elemente kann dein Partner aufzählen?": "Wasserstoff (H),Helium (He),Kohlenstoff (C),Sauerstoff (O),Gold (Au),Silber (Ag),Eisen (Fe)",

        // --- Allgemeinwissen & Sonstiges ---
        "Wie viele Präsidenten kann dein Partner nennen?": "Obama,Trump,Biden,Kennedy (JFK),Lincoln,Washington,Putin,Macron,Erdogan",
        "Wie viele Vornamen mit drei Buchstaben kann dein Partner nennen?": "Tim,Tom,Ben,Lea,Mia,Pia,Leo,Max,Jan,Joy,Ali,Bob",
        "Wie viele Vornamen, die auf \"y\" enden, kennt dein Partner?": "Tommy,Jenny,Henry,Emily,Lilly,Joy,Romy,Tony,Freddy,Harry",
        "Wie viele Feiertage kann dein Partner aufzählen?": "Weihnachten,Ostern,Pfingsten,Halloween,Valentinstag,Neujahr,Tag der Arbeit,Muttertag,Nikolaus",
        "Wie viele Musikinstrumente kann dein Partner nennen?": "Gitarre,Klavier,Geige,Schlagzeug,Flöte,Trompete,Saxophon,Bass,Cello,Klarinette",
        "Wie viele berühmte Maler kann dein Partner aufzählen?": "Picasso,Van Gogh,Da Vinci,Monet,Rembrandt,Dali,Michelangelo,Warhol",
        "Wie viele Programmiersprachen fallen deinem Partner ein?": "Python,Java,C++,Swift,JavaScript,HTML,CSS,PHP,Ruby,C#",
        "Wie viele Nobelpreisträger in Physik fallen deinem Partner ein?": "Albert Einstein,Marie Curie,Max Planck,Heisenberg,Niels Bohr,Schrödinger,Röntgen",
        "Wie viele Cocktails kann dein Partner nennen?": "Mojito,Sex on the Beach,Pina Colada,Gin Tonic,Margarita,Cosmopolitan,Caipirinha,Aperol Spritz",
        "Wie viele lateinische Redewendungen kennt dein Partner?": "Carpe Diem,Veni Vidi Vici,Et tu Brute,In Vino Veritas,Alea iacta est,Memento Mori",
        "Wie viele Schulfächer fallen deinem Partner ein?": "Mathe,Deutsch,Englisch,Sport,Kunst,Musik,Biologie,Geschichte,Chemie,Physik,Erdkunde",
        "Wie viele Cocktailzutaten kann dein Partner nennen?": "Rum,Wodka,Gin,Tequila,Limette,Zucker,Minze,Orange,Ananas,Eiswürfel",
        "Wie viele Festtage weltweit kann dein Partner nennen?": "Weihnachten,Ostern,Halloween,Eid al-Fitr (Zuckerfest),Chanukka,Thanksgiving,Diwali,St. Patrick's Day",
        "Wie viele Startup-Logos erkennt dein Partner?": "Uber,Airbnb,Spotify,Slack,Stripe,Revolut,Gorillas,N26,Tinder",
        "Wie viele Nobelpreisträger in Frieden kann dein Partner nennen?": "Nelson Mandela,Barack Obama,Mutter Teresa,Dalai Lama,Malala,Martin Luther King,Willy Brandt",
        "Wie viele deutsche Bundeskanzler:innen kann dein Partner aufzählen?": "Olaf Scholz,Angela Merkel,Gerhard Schröder,Helmut Kohl,Helmut Schmidt,Willy Brandt,Adenauer",
        "Wie viele Sprachen der Welt kann dein Partner nennen?": "Englisch,Spanisch,Französisch,Deutsch,Italienisch,Portugiesisch,Arabisch,Chinesisch,Russisch,Japanisch",
        "Wie viele berühmte Architekten kann dein Partner nennen?": "Zaha Hadid,Norman Foster,Le Corbusier,Gaudí,Walter Gropius,Frank Gehry",
        "Wie viele berühmte Tänze oder Tanzstile kennt dein Partner?": "Walzer,Tango,Salsa,Cha-Cha-Cha,Rumba,Foxtrott,Disco Fox,Hip Hop,Ballett",
        "Wie viele Autobahnen oder Bundesstraßen kennt dein Partner?": "A1,A2,A3,A4,A5,A6,A7,A8,A9,B1,B9,Route 66",
        "Wie viele Musikinstrumente mit Saiten fallen deinem Partner ein?": "Gitarre,Geige,Cello,Harfe,Bass,Banjo,Ukulele,Bratsche,Mandoline",
        "Wie viele berühmte Köche oder Kochshows kennt dein Partner?": "Gordon Ramsay,Jamie Oliver,Tim Mälzer,The Taste,Kitchen Impossible,Henssler,Lichter",
        
        // --- Persönliches / Kontextabhängig (Hinweise für Schiedsrichter) ---
        "Wie viele Liegestütze kann dein Partner?": "Schiedsrichter zählt mit! Saubere Ausführung beachten!",
        "Wie lange kann dein Partner die Luft anhalten?": "Stoppuhr nutzen! Nase zuhalten erlaubt.",
        "Wie lange kann dein Partner nicht blinzeln?": "Starr-Wettbewerb! Wer zuerst blinzelt verliert.",
        "Wie viele Tools/Apps nutzt dein Partner täglich?": "WhatsApp,Instagram,TikTok,YouTube,Spotify,Google Maps,Mail,Browser,Kamera,Kalender",
        "Wie viele Songtexte kann dein Partner auswendig?": "Einfach anstimmen lassen! Schiedsrichter entscheidet, ob es zählt.",
        "Wie viele Apps auf deinem Handy nutzt dein Partner täglich?": "WhatsApp,Instagram,TikTok,YouTube,Spotify,Maps,Mail,Banking,Wetter",
        "Wie viele beliebte Cocktail-Bars in eurer Stadt kennt dein Partner?": "Lokale Bars zählen lassen! Schiedsrichter entscheidet.",
        "Wie viele Theater in eurer Stadt kann dein Partner nennen?": "Lokale Theater zählen lassen! Schiedsrichter entscheidet.",
        
        // --- NEUE HINWEISE (Erweiterung) ---
                
                // Geografie
                "Wie viele Bundesländer in Deutschland kann dein Partner aufzählen?": "Bayern,NRW,Baden-Württemberg,Hessen,Sachsen,Thüringen,Berlin,Hamburg,Bremen,Saarland,Brandenburg",
                "Wie viele Nachbarländer von Deutschland kann dein Partner nennen?": "Dänemark,Polen,Tschechien,Österreich,Schweiz,Frankreich,Luxemburg,Belgien,Niederlande",
                "Wie viele Hauptstädte in Asien kennt dein Partner?": "Tokio,Peking,Bangkok,Seoul,Neu-Delhi,Hanoi,Jakarta,Teheran,Riad,Manila,Kuala Lumpur",
                "Wie viele Städte in Frankreich kann dein Partner aufzählen?": "Paris,Marseille,Lyon,Toulouse,Nizza,Nantes,Straßburg,Montpellier,Bordeaux,Lille",
                "Wie viele Ozeane oder Weltmeere kennt dein Partner?": "Pazifik,Atlantik,Indischer Ozean,Arktischer Ozean,Antarktischer Ozean,Mittelmeer,Karibik,Nordsee,Ostsee",
                "Wie viele Währungen (außer Euro/Dollar) fallen deinem Partner ein?": "Pfund,Yen,Franken,Rubel,Rupie,Won,Lira,Peso,Rand,Real,Krone,Dirham",
                "Wie viele Kantone der Schweiz kann dein Partner nennen?": "Zürich,Bern,Luzern,Uri,Schwyz,Zug,Freiburg,Basel,St. Gallen,Graubünden,Aargau,Tessin,Waadt,Genf",
                "Wie viele Bundesstaaten der USA an der Westküste kennt dein Partner?": "Kalifornien,Oregon,Washington,Alaska (geografisch),Hawaii (pazifisch)",

                // Natur & Tiere
                "Wie viele Hunderassen kann dein Partner aufzählen?": "Schäferhund,Labrador,Golden Retriever,Bulldogge,Pudel,Chihuahua,Dackel,Husky,Beagle,Rottweiler,Boxer",
                "Wie viele Katzenrassen kennt dein Partner?": "Perser,Maine Coon,Siam,Bengal,British Shorthair,Ragdoll,Sphynx,Norwegische Waldkatze,Birma",
                "Wie viele Dinosaurier-Namen fallen deinem Partner ein?": "T-Rex,Triceratops,Velociraptor,Stegosaurus,Brachiosaurus,Diplodocus,Ankylosaurus,Spinosaurus",
                "Wie viele Hai-Arten kann dein Partner nennen?": "Weißer Hai,Hammerhai,Tigerhai,Bullenhai,Walhai,Mako,Riffhai,Blauhai,Engelshai",
                "Wie viele Vogelarten (heimisch) kennt dein Partner?": "Amsel,Drossel,Fink,Star,Spatz,Meise,Rotkehlchen,Taube,Krähe,Elster,Specht,Adler",
                "Wie viele Blumensorten kann dein Partner aufzählen?": "Rose,Tulpe,Sonnenblume,Nelke,Lilie,Orchidee,Gänseblümchen,Mohn,Veilchen,Narzisse",
                "Wie viele Obstsorten fallen deinem Partner ein?": "Apfel,Banane,Birne,Orange,Pfirsich,Kirsche,Pflaume,Mango,Ananas,Kiwi,Weintraube",
                "Wie viele Beerenarten kann dein Partner nennen?": "Erdbeere,Himbeere,Blaubeere,Brombeere,Johannisbeere,Stachelbeere,Preiselbeere,Holunderbeere",
                "Wie viele Nusssorten kennt dein Partner?": "Walnuss,Haselnuss,Erdnuss,Cashew,Mandel,Pistazie,Macadamia,Paranuss,Pecan",
                "Wie viele essbare Pilzsorten fallen deinem Partner ein?": "Champignon,Pfifferling,Steinpilz,Austernpilz,Trüffel,Shiitake,Kräuterseitling,Morchel",

                // Popkultur
                "Wie viele James-Bond-Filme (Titel) kann dein Partner nennen?": "Goldfinger,Casino Royale,Skyfall,Spectre,No Time to Die,Dr. No,GoldenEye,Moonraker",
                "Wie viele Star-Wars-Filme oder -Serien fallen deinem Partner ein?": "Eine neue Hoffnung,Das Imperium schlägt zurück,Die Rückkehr der Jedi-Ritter,Phantom Menace,Mandalorian,Ahsoka,Andor",
                "Wie viele Marvel-Filme (MCU) kann dein Partner aufzählen?": "Iron Man,Avengers,Thor,Captain America,Black Panther,Guardians of the Galaxy,Spider-Man,Doctor Strange",
                "Wie viele Charaktere aus 'Game of Thrones' kennt dein Partner?": "Jon Schnee,Daenerys,Tyrion,Cersei,Arya,Sansa,Jaime,Bran,Joffrey,Khal Drogo",
                "Wie viele bekannte Sitcoms kann dein Partner nennen?": "Friends,How I Met Your Mother,Big Bang Theory,Two and a Half Men,Brooklyn 99,Modern Family,Scrubs,King of Queens",
                "Wie viele Zeichentrickserien aus den 90ern/2000ern kennt dein Partner?": "SpongeBob,Simpsons,Pokémon,Dragon Ball,Sailor Moon,Gummibärenbande,DuckTales,Darkwing Duck",
                "Wie viele Pokémon der 1. Generation kann dein Partner nennen?": "Pikachu,Glumanda,Schiggy,Bisasam,Glurak,Mewtu,Relaxo,Evoli,Mauzi,Enton,Pummeluff",
                "Wie viele Erweiterungspacks von 'Die Sims' fallen deinem Partner ein?": "Haustiere,Vier Jahreszeiten,Inselparadies,An die Uni,Wer werde berühmt,Reiseabenteuer,Late Night",
                "Wie viele Teile von 'Grand Theft Auto' (GTA) kennt dein Partner?": "GTA V,GTA IV,San Andreas,Vice City,GTA III,GTA Online",
                "Wie viele Teile von 'Call of Duty' fallen deinem Partner ein?": "Modern Warfare,Black Ops,Warzone,World at War,Vanguard,Cold War,Ghosts",
                "Wie viele bekannte Anime-Serien kann dein Partner nennen?": "One Piece,Naruto,Dragon Ball,Attack on Titan,Death Note,Demon Slayer,Sailor Moon,Pokémon",

                // Marken & Alltag
                "Wie viele Fast-Food-Ketten kennt dein Partner?": "McDonald's,Burger King,KFC,Subway,Pizza Hut,Domino's,Five Guys,Dunkin Donuts,Starbucks",
                "Wie viele große Möbelhäuser kann dein Partner nennen?": "IKEA,XXL Lutz,Mömax,Höffner,Segmüller,Roller,Poco,Dänisches Bettenlager (Jysk)",
                "Wie viele Baumarkt-Ketten fallen deinem Partner ein?": "Obi,Hornbach,Bauhaus,Toom,Hagebau,Globus,Hellweg",
                "Wie viele Tankstellen-Marken kennt dein Partner?": "Aral,Shell,Esso,Total,Jet,Agip (Eni),Hem,OMV,Star",
                "Wie viele Drogeriemärkte kann dein Partner aufzählen?": "dm,Rossmann,Müller,Budni,Douglas",
                "Wie viele Banken oder Sparkassen kennt dein Partner?": "Deutsche Bank,Commerzbank,Sparkasse,Volksbank,Postbank,ING,DKB,Targobank,HypoVereinsbank",
                "Wie viele Versicherungen fallen deinem Partner ein?": "Allianz,AXA,Ergo,HUK Coburg,Debeka,Generali,R+V,DEVK,Signal Iduna",
                "Wie viele deutsche Biermarken kann dein Partner nennen?": "Krombacher,Bitburger,Warsteiner,Becks,Paulaner,Erdinger,Veltins,Radeberger,Augustiner,Jever",
                "Wie viele Kaffeespezialitäten kann dein Partner aufzählen?": "Espresso,Cappuccino,Latte Macchiato,Americano,Flat White,Mokka,Cortado,Eiskaffee",
                "Wie viele Brotsorten kennt dein Partner?": "Weißbrot,Graubrot,Vollkornbrot,Roggenbrot,Pumpernickel,Baguette,Ciabatta,Toastbrot,Dinkelbrot",

                // Sport & Wissen
                "Wie viele Formel-1-Fahrer (aktuell oder Legenden) kennt dein Partner?": "Schumacher,Hamilton,Verstappen,Vettel,Senna,Lauda,Prost,Rosberg,Alonso,Leclerc",
                "Wie viele NBA-Teams (Basketball) kann dein Partner nennen?": "Lakers,Bulls,Warriors,Celtics,Knicks,Heat,Spurs,Mavericks,Raptors,Nets",
                "Wie viele NFL-Teams (Football) fallen deinem Partner ein?": "Patriots,Chiefs,Cowboys,49ers,Packers,Eagles,Steelers,Dolphins,Giants,Broncos",
                "Wie viele Disziplinen der Olympischen Winterspiele kennt dein Partner?": "Biathlon,Skispringen,Ski Alpin,Bob,Rodeln,Eishockey,Curling,Eiskunstlauf,Snowboard",
                "Wie viele Gürtelfarben im Kampfsport (Judo/Karate) kann dein Partner nennen?": "Weiß,Gelb,Orange,Grün,Blau,Braun,Schwarz,Rot (Meister)",
                "Wie viele Schachfiguren (Bezeichnungen) kennt dein Partner?": "König,Dame,Turm,Läufer,Springer (Pferd),Bauer",
                "Wie viele berühmte Komponisten (Klassik) fallen deinem Partner ein?": "Mozart,Beethoven,Bach,Vivaldi,Chopin,Wagner,Verdi,Tschaikowsky,Schubert",
                "Wie viele berühmte Philosophen kann dein Partner nennen?": "Sokrates,Platon,Aristoteles,Kant,Nietzsche,Descartes,Hegel,Marx,Seneca",
                "Wie viele Römische Götter kennt dein Partner?": "Jupiter,Mars,Venus,Neptun,Merkur,Apollo,Diana,Minerva,Juno,Vulcanus",
                "Wie viele Organe des menschlichen Körpers kann dein Partner aufzählen?": "Herz,Lunge,Leber,Niere,Magen,Gehirn,Darm,Haut,Milz,Bauchspeicheldrüse",
        // MARK: - Neue Classic Erweiterung (Lösungen)

                "Wie viele Weltwunder (Antike oder Neuzeit) kann dein Partner nennen?": "Pyramiden von Gizeh,Hängende Gärten der Semiramis,Koloss von Rhodos,Zeus-Statue,Tempel der Artemis,Mausoleum von Halikarnassos,Leuchtturm von Pharos,Chinesische Mauer,Petra,Kolosseum,Machu Picchu,Chichén Itzá,Taj Mahal,Christo Redentor",
                "Wie viele Bundespräsidenten der Bundesrepublik Deutschland fallen deinem Partner ein?": "Theodor Heuss,Heinrich Lübke,Gustav Heinemann,Walter Scheel,Karl Carstens,Richard von Weizsäcker,Roman Herzog,Johannes Rau,Horst Köhler,Christian Wulff,Joachim Gauck,Frank-Walter Steinmeier",
                "Wie viele Einheiten für Längenmaße (z.B. Meter, Zoll) kennt dein Partner?": "Millimeter,Zentimeter,Dezimeter,Meter,Kilometer,Zoll (Inch),Fuß (Foot),Meile,Yard,Lichtjahr,Seemeile,Elle,Parsec,Ångström",
                "Wie viele Einheiten für Gewicht (z.B. Gramm, Pfund) kann dein Partner aufzählen?": "Milligramm,Gramm,Kilogramm,Tonne,Pfund,Unze,Zentner,Karat,Stone,Grain,Doppelzentner",
                "Wie viele Aggregatzustände kennt dein Partner?": "Fest,Flüssig,Gasförmig,Plasma,Bose-Einstein-Kondensat",
                "Wie viele Arten von Niederschlag (z.B. Hagel, Niesel) kann dein Partner nennen?": "Regen,Schnee,Hagel,Graupel,Nieselregen,Schneeregen,Tau,Reif,Eisregen,Industrieschnee",
                "Wie viele Chinesische Tierkreiszeichen kennt dein Partner?": "Ratte,Büffel,Tiger,Hase,Drache,Schlange,Pferd,Ziege (Schaf),Affe,Hahn,Hund,Schwein",
                "Wie viele Namen der Finger (z.B. Ringfinger) kann dein Partner aufzählen?": "Daumen,Zeigefinger,Mittelfinger,Ringfinger,Kleiner Finger",
                "Wie viele Satzzeichen kann dein Partner nennen?": "Punkt,Komma,Ausrufezeichen,Fragezeichen,Doppelpunkt,Semikolon (Strichpunkt),Bindestrich,Gedankenstrich,Anführungszeichen,Klammer,Apostroph,Schrägstrich,Sternchen",
                "Wie viele Wortarten (z.B. Nomen, Verb) fallen deinem Partner ein?": "Nomen (Substantiv),Verb,Adjektiv,Artikel,Pronomen,Adverb,Präposition,Konjunktion,Interjektion,Numerale",
                "Wie viele Zeitformen in der Grammatik (z.B. Futur, Präteritum) kennt dein Partner?": "Präsens,Präteritum (Imperfekt),Perfekt,Plusquamperfekt,Futur I,Futur II",
                "Wie viele Nadelbaum-Arten kann dein Partner aufzählen?": "Fichte,Tanne,Kiefer,Lärche,Eibe,Douglasie,Zeder,Mammutbaum,Zypresse,Wacholder,Araukarie,Thuja",
                "Wie viele Laubbaum-Arten fallen deinem Partner ein?": "Eiche,Buche,Ahorn,Birke,Linde,Kastanie,Esche,Pappel,Weide,Erle,Ulme,Platane,Walnussbaum,Haselnuss,Kirschbaum",
                "Wie viele Raubkatzen-Arten (z.B. Löwe, Puma) kennt dein Partner?": "Löwe,Tiger,Leopard,Jaguar,Schneeleopard,Gepard,Puma (Berglöwe),Luchs,Serval,Ozelot,Karakal,Nebelparder",
                "Wie viele Schlangenarten kann dein Partner nennen?": "Kobra,Klapperschlange,Python,Boa Constrictor,Anakonda,Kreuzotter,Ringelnatter,Mamba,Taipan,Viper,Blindschleiche (technisch Echse aber oft genannt),Kornnatter",
                "Wie viele Himmelsrichtungen (inkl. Zwischenrichtungen wie Nordost) kennt dein Partner?": "Norden,Osten,Süden,Westen,Nordost,Südost,Südwest,Nordwest,Nordnordost,Ostsüdost",
                "Wie viele Kontinente kann dein Partner aufzählen?": "Europa,Asien,Afrika,Nordamerika,Südamerika,Australien (Ozeanien),Antarktis",
                "Wie viele Zwergstaaten in Europa (z.B. Monaco) kann dein Partner nennen?": "Vatikanstadt,Monaco,San Marino,Liechtenstein,Andorra,Malta",
                "Wie viele Nachbarländer von Österreich kennt dein Partner?": "Deutschland,Tschechien,Slowakei,Ungarn,Slowenien,Italien,Schweiz,Liechtenstein",
                "Wie viele Flüsse in den USA kann dein Partner aufzählen?": "Mississippi,Missouri,Yukon,Rio Grande,Colorado River,Hudson River,Columbia River,Ohio River,Arkansas River,Snake River,Tennessee River",
                "Wie viele Berge in den Alpen kennt dein Partner?": "Zugspitze,Mont Blanc,Matterhorn,Großglockner,Eiger,Mönch,Jungfrau,Dolomiten (Gebirgsgruppe),Watzmann,Dufourspitze,Ortler,Piz Buin",
                "Wie viele Inseln im Mittelmeer kann dein Partner nennen?": "Mallorca,Ibiza,Sardinien,Korsika,Sizilien,Kreta,Zypern,Malta,Rhodos,Korfu,Menorca,Elba,Santorin,Mykonos",
                "Wie viele Museen in eurer Stadt kennt dein Partner?": "Heimatmuseum,Kunstmuseum,Naturkundemuseum,Technikmuseum,Historisches Museum,Stadtmuseum,Spielzeugmuseum (Antwort ist ortsabhängig!)",
                "Wie viele Brückenarten (z.B. Hängebrücke) kennt dein Partner?": "Hängebrücke,Bogenbrücke,Balkenbrücke,Schrägseilbrücke,Hubbrücke,Zugbrücke,Pontonbrücke,Viadukt,Aquädukt,Kettenbrücke",
                "Wie viele geometrische Formen (2D) kann dein Partner aufzählen?": "Kreis,Quadrat,Rechteck,Dreieck,Oval,Raute,Trapez,Parallelogramm,Fünfeck,Sechseck,Achteck",
                "Wie viele geometrische Körper (3D) fallen deinem Partner ein?": "Würfel,Kugel,Quader,Zylinder,Kegel,Pyramide,Prisma,Tetraeder,Oktaeder,Dodekaeder",
                "Wie viele Bestandteile eines Fahrrads kann dein Partner benennen?": "Lenker,Sattel,Pedale,Kette,Reifen,Speichen,Felge,Bremse,Gangschaltung,Rahmen,Gabel,Klingel,Licht,Gepäckträger,Ventil",
                "Wie viele Bestandteile eines Autos (Karosserie) kennt dein Partner?": "Motorhaube,Kofferraum,Tür,Kotflügel,Stoßstange,Dach,Windschutzscheibe,Seitenspiegel,Scheinwerfer,Rücklicht,Kühlergrill,Radkasten,Auspuff",
                "Wie viele verschiedene Handwerksberufe kann dein Partner aufzählen?": "Schreiner/Tischler,Zimmermann,Maurer,Dachdecker,Klempner,Elektriker,Maler,Bäcker,Metzger,Friseur,Schneider,Schmied,Töpfer,Glaser",
                "Wie viele Adelstitel (z.B. Graf, Herzog) kennt dein Partner?": "Kaiser,König,Herzog,Fürst,Graf,Baron,Freiherr,Ritter,Prinz,Kurfürst,Erzherzog,Markgraf",

        // --- Fehlende Hinweise (Ergänzung) ---
        "Wie viele Fußballvereine aus der Bundesliga kennt dein Partner?": "Bayern München,Borussia Dortmund,RB Leipzig,Bayer Leverkusen,Eintracht Frankfurt,Werder Bremen,VfB Stuttgart,Schalke 04,Hertha BSC,VfL Wolfsburg,FSV Mainz 05,SC Freiburg,FC Augsburg,1. FC Köln,Union Berlin",
        "Wie viele Fluggesellschaften kennt dein Partner?": "Lufthansa,Eurowings,Ryanair,EasyJet,British Airways,Air France,KLM,Emirates,Qatar Airways,Turkish Airlines,United Airlines,Delta,American Airlines,Swiss,Austrian Airlines",
        "Wie viele Griechische Götter kann dein Partner nennen?": "Zeus,Hera,Poseidon,Hades,Athene,Ares,Apollo,Artemis,Aphrodite,Hermes,Hephaistos,Demeter,Hestia,Dionysos",
        "Wie viele Flughäfen mit drei Buchstaben kennt dein Partner (IATA-Codes)?": "FRA,MUC,BER,LHR,CDG,JFK,LAX,AMS,DXB,SYD,HND,SFO,BCN,IST,DUB",
        "Wie viele Dinge kann dein Partner nennen, die man in einem Koffer packt?": "Kleidung,Unterwäsche,Socken,Schuhe,Zahnbürste,Zahnpasta,Ladegerät,Reisepass,Medikamente,Buch,Handtuch,Sonnencreme,Regenjacke,Adapter,Schlafanzug",
        "Wie viele Haushaltsgeräte kann dein Partner aufzählen?": "Kühlschrank,Waschmaschine,Spülmaschine,Backofen,Toaster,Mikrowelle,Staubsauger,Kaffeemaschine,Wasserkocher,Föhn,Bügeleisen,TV,Radio,Klimagerät,Staubsaugerroboter",
        "Wie viele Küchenutensilien kann dein Partner nennen?": "Messer,Schneidebrett,Topf,Pfanne,Kochlöffel,Schöpfkelle,Schneebesen,Spatel,Sieb,Messbecher,Dosenöffner,Küchenreibe,Schüssel,Zange,Backblech",
        "Wie viele Möbelstücke fallen deinem Partner ein?": "Sofa,Stuhl,Tisch,Bett,Schrank,Kommode,Regal,Nachttisch,Schreibtisch,Sessel,Sideboard,TV-Board,Esstisch,Bücherregal,Garderobe",
        "Wie viele Reinigungsmittel oder Putzutensilien kennt dein Partner?": "Allzweckreiniger,Glasreiniger,Badreiniger,WC-Reiniger,Bodenreiniger,Spülmittel,Schwamm,Mikrofasertuch,Besen,Wischmopp,Eimer,Staubwedel,Schrubber,Entkalker,Backofenreiniger",
        "Wie viele Dinge kann dein Partner nennen, die man im Badezimmer findet?": "Zahnbürste,Zahnpasta,Handtuch,Duschgel,Shampoo,Conditioner,Seife,Toilettenpapier,Deo,Parfüm,Rasierer,Spiegel,Föhn,Waschbecken,Toilette",
        "Wie viele Apps auf deinem Handy kann dein Partner erraten/nennen?": "WhatsApp,Instagram,TikTok,YouTube,Spotify,Google Maps,Mail,Kamera,Browser,Kalender,Facebook,Netflix,Amazon,Notizen,Wetter",
        "Wie viele Dinge kann dein Partner nennen, die man im Auto immer dabei haben sollte?": "Führerschein,Fahrzeugschein,Warnweste,Warndreieck,Verbandskasten,Eiskratzer,Ladekabel,Parkuhr,Regenschirm,Wasserflasche,Starthilfekabel,Feuerlöscher,Reserverad,Notfallnummern,Taschenlampe",
        "Wie viele italienische Gerichte kann dein Partner nennen?": "Pizza,Spaghetti Carbonara,Lasagne,Risotto,Gnocchi,Bruschetta,Osso Buco,Caprese,Tiramisu,Arancini,Tagliatelle al Ragù,Calzone,Polenta,Pesto Pasta,Parmigiana",
        "Wie viele vegetarische Gerichte fallen deinem Partner ein?": "Gemüsecurry,Vegetarische Lasagne,Caprese,Salat,Falafel,Vegetarische Pizza,Spinatlasagne,Ofengemüse,Shakshuka,Chili sin Carne,Vegetarische Wraps,Quiche,Tomatensuppe,Gemüsepfanne,Bratkartoffeln",
        "Wie viele Küchen der Welt kann dein Partner nennen (z.B. italienisch, indisch)?": "Italienisch,Indisch,Chinesisch,Japanisch,Thailändisch,Französisch,Spanisch,Griechisch,Türkisch,Arabisch,Amerikanisch,Mexikanisch,Vietnamesisch,Koreanisch,Brasilianisch",
        "Wie viele Suppenarten kann dein Partner aufzählen?": "Tomatensuppe,Kürbissuppe,Gulaschsuppe,Hühnersuppe,Linsensuppe,Erbsensuppe,Zwiebelsuppe,Minestrone,Kartoffelsuppe,Champignonsuppe,Fischsuppe,Ramen,Pho,Klare Brühe",
        "Wie viele Obstsorten, die gelb sind, kann dein Partner nennen?": "Banane,Zitrone,Ananas,Mango,Grapefruit,Mirabelle,Aprikose,Goldkiwi,Quitte,Honigmelone,Gelber Apfel,Gelbe Pflaume,Papaya",
        "Wie viele Fast-Food-Produkte (z.B. Burger-Arten) kann dein Partner aufzählen?": "Hamburger,Cheeseburger,Chickenburger,Fischburger,Double Burger,Bacon Burger,Wrap,Nuggets,Pommes,Zwiebelringe,Hot Dog,Milkshake,Salat,Chicken Wings,Chili Cheese Fries",
        "Wie viele Teesorten kann dein Partner nennen?": "Schwarztee,Grüntee,Pfefferminze,Kamille,Rooibos,Früchtetee,Hibiskus,Earl Grey,Chai,Weißer Tee,Oolong,Salbei,Ingwer,Brennessel,Melisse",
        "Wie viele Kaffeegetränke kann dein Partner aufzählen?": "Espresso,Americano,Cappuccino,Latte Macchiato,Milchkaffee,Flat White,Mokka,Macchiato,Irish Coffee,Eiskaffee,Cold Brew,Filterkaffee,Ristretto,Frappé,Affogato",
        "Wie viele Frühstücks-Sachen kann dein Partner nennen?": "Brot,Brötchen,Butter,Marmelade,Honig,Käse,Wurst,Müsli,Haferflocken,Joghurt,Obst,Eier,Saft,Kaffee,Milch",
        "Wie viele Snacks (Chips, Riegel, etc.) kann dein Partner aufzählen?": "Chips,Popcorn,Nüsse,Schokoriegel,Gummibärchen,Cracker,Salzstangen,Müsliriegel,Nachos,Studentenfutter,Reiswaffeln,Brezeln,Schokolade,Obst,Jerky",
        "Wie viele UNESCO-Welterbestätten kann dein Partner nennen?": "Kölner Dom,Akropolis,Chinesische Mauer,Kolosseum,Petra,Machu Picchu,Taj Mahal,Angkor Wat,Stonehenge,Alhambra,Great Barrier Reef,Galápagos,Serengeti,Venedig,Mont-Saint-Michel",
        "Wie viele Inseln in Griechenland fallen deinem Partner ein?": "Kreta,Rhodos,Santorin,Mykonos,Korfu,Kos,Lesbos,Samos,Zakynthos,Chios,Naxos,Paros,Thasos,Karpathos",
        "Wie viele Städte in der Türkei kann dein Partner aufzählen?": "Istanbul,Ankara,Izmir,Antalya,Bursa,Adana,Gaziantep,Konya,Mersin,Trabzon,Kayseri,Eskişehir",
        "Wie viele Städte in den USA kann dein Partner nennen?": "New York,Los Angeles,Chicago,Houston,Phoenix,Philadelphia,San Antonio,San Diego,Dallas,San Jose,Miami,Seattle,Boston,Las Vegas,Washington D.C.",
        "Wie viele Länder in Südamerika kann dein Partner aufzählen?": "Argentinien,Bolivien,Brasilien,Chile,Kolumbien,Ecuador,Guyana,Paraguay,Peru,Suriname,Uruguay,Venezuela",
        "Wie viele Länder in Europa kann dein Partner nennen?": "Deutschland,Frankreich,Italien,Spanien,Portugal,Niederlande,Belgien,Schweiz,Österreich,Polen,Schweden,Norwegen,Griechenland,Tschechien,Ungarn",
        "Wie viele Gebirge in Europa fallen deinem Partner ein?": "Alpen,Pyrenäen,Karpaten,Apennin,Skandinavisches Gebirge,Balkan,Dinariden,Massif Central,Schottische Highlands,Kaukasus,Ural",
        "Wie viele Seen in Deutschland kann dein Partner nennen?": "Bodensee,Müritz,Chiemsee,Starnberger See,Ammersee,Wannsee,Steinhuder Meer,Schweriner See,Plauer See,Edersee,Tegernsee,Altmühlsee",
        "Wie viele bekannte Rapper aus Deutschland kann dein Partner nennen?": "Sido,Bushido,Capital Bra,Apache 207,Cro,RAF Camora,Bonez MC,Eko Fresh,Samy Deluxe,Shindy,Kollegah,Farid Bang,Kontra K,Haftbefehl,Peter Fox",
        "Wie viele bekannte Rapper aus den USA kann dein Partner aufzählen?": "Eminem,Jay-Z,Kanye West,Tupac,The Notorious B.I.G.,Drake,Kendrick Lamar,Lil Wayne,Nas,Snoop Dogg,50 Cent,Travis Scott,Nicki Minaj,Cardi B,Post Malone",
        "Wie viele Schauspieler:innen aus deutschen Filmen/Serien kann dein Partner nennen?": "Til Schweiger,Matthias Schweighöfer,Elyas M'Barek,Diane Kruger,Heiner Lauterbach,Veronica Ferres,Jürgen Vogel,Daniel Brühl,Nora Tschirner,Florian David Fitz,Lars Eidinger,Moritz Bleibtreu,Karoline Herfurth,Christoph Waltz,Tom Schilling",
        "Wie viele Reality-TV-Formate kann dein Partner aufzählen?": "Big Brother,Promi Big Brother,Der Bachelor,Love Island,Temptation Island,Bauer sucht Frau,Take Me Out,DSDS,The Voice of Germany,GNTM,Supertalent,Sommerhaus der Stars,Kampf der Realitystars,Are You The One?,Die Bachelorette",
        "Wie viele bekannte TikToker oder Influencer kann dein Partner nennen?": "Charli D'Amelio,Addison Rae,Khaby Lame,Bella Poarch,Pamela Reif,BibisBeautyPalace,Rezo,Julien Bam,Knossi,MontanaBlack,Dagi Bee,Trymacs,Younes Zarou,Caro Daur,MrBeast",
        "Wie viele berühmte Serien-Charaktere kann dein Partner nennen?": "Homer Simpson,Walter White,Jon Snow,Daenerys Targaryen,Tyrion Lannister,Sherlock Holmes,Michael Scott,Rachel Green,Chandler Bing,Sheldon Cooper,Eleven,Rick Grimes,Dexter Morgan,Harvey Specter",
        "Wie viele Film-Genres kann dein Partner aufzählen?": "Action,Komödie,Drama,Horror,Thriller,Sci-Fi,Fantasy,Romantik,Krimi,Animation,Dokumentation,Abenteuer,Mystery,Western,Musical",
        "Wie viele Disney-Lieder kann dein Partner nennen?": "Hakuna Matata,Let It Go,Can You Feel the Love Tonight,A Whole New World,Under the Sea,Part of Your World,Be Our Guest,Circle of Life,Friend Like Me,I'll Make a Man Out of You,Do You Want to Build a Snowman?,How Far I'll Go,Colors of the Wind,You've Got a Friend in Me",
        "Wie viele Superhelden-Namen (Marvel/DC gemischt) fallen deinem Partner ein?": "Spider-Man,Batman,Superman,Wonder Woman,Iron Man,Captain America,Thor,Hulk,Black Panther,Flash,Green Lantern,Aquaman,Doctor Strange,Ant-Man,Wolverine",
        "Wie viele deutsche YouTube-Kanäle kann dein Partner nennen?": "Gronkh,Rezo,BibisBeautyPalace,Julien Bam,LeFloid,Unge,Dagi Bee,Paluten,Trymacs,MontanaBlack,Knossi,HandOfBlood,MrWissen2go,TheSimpleClub,Bonjwa",
        "Wie viele Fußballvereine aus Europa kann dein Partner nennen?": "Real Madrid,FC Barcelona,Manchester United,Manchester City,FC Liverpool,Arsenal,Chelsea,Juventus,AC Milan,Inter Mailand,Bayern München,Borussia Dortmund,Paris Saint-Germain,Ajax,FC Porto",
        "Wie viele Fußballstadien kann dein Partner aufzählen?": "Allianz Arena,Signal Iduna Park,Wembley,Camp Nou,Santiago Bernabéu,San Siro,Old Trafford,Anfield,Stamford Bridge,Parc des Princes,Maracanã,Olympiastadion Berlin,Stadio Olimpico",
        "Wie viele Fitnessübungen ohne Geräte kann dein Partner nennen?": "Liegestütze,Kniebeugen,Ausfallschritte,Plank,Sit-ups,Crunches,Burpees,Bergsteiger,Jumping Jacks,Wandsitz,Trizeps-Dips,Hampelmann,Superman,Beinheben,Brücke",
        "Wie viele Cardio-Arten fallen deinem Partner ein?": "Joggen,Laufen,Sprinten,Radfahren,Schwimmen,Seilspringen,HIIT,Zumba,Tanzen,Rudern,Walking,Treppensteigen,Spinning,Inline-Skaten,Boxen",
        "Wie viele Kampfsportarten kann dein Partner aufzählen?": "Judo,Karate,Taekwondo,Boxen,Kickboxen,Muay Thai,Brazilian Jiu-Jitsu,Jiu-Jitsu,Aikido,Kung Fu,MMA,Capoeira,Krav Maga,Ringen,Fechten",
        "Wie viele Sportmarken (Nike, Adidas, etc.) kann dein Partner nennen?": "Nike,Adidas,Puma,Reebok,Under Armour,Asics,New Balance,Fila,Champion,Diadora,Lotto,Salomon,The North Face,Columbia,Kappa",
        "Wie viele berühmte Fußballerinnen kann dein Partner nennen?": "Marta,Alex Morgan,Megan Rapinoe,Sam Kerr,Alexia Putellas,Alexandra Popp,Lena Oberdorf,Lea Schüller,Birgit Prinz,Carli Lloyd,Hope Solo,Abby Wambach,Marie-Antoinette Katoto,Lucy Bronze",
        "Wie viele berühmte Tennisspieler:innen kann dein Partner aufzählen?": "Roger Federer,Rafael Nadal,Novak Djokovic,Serena Williams,Venus Williams,Steffi Graf,Boris Becker,Andy Murray,Andre Agassi,Naomi Osaka,Martina Navratilova,Pete Sampras,Maria Sharapova,Caroline Wozniacki",
        "Wie viele Länderflaggen kann dein Partner beschreiben (ohne Namen zu sagen)?": "Deutschland,Frankreich,Italien,USA,Großbritannien,Kanada,Japan,Brasilien,Spanien,Griechenland,Schweiz,Schweden,Norwegen,China,Russland",
        "Wie viele Automarken-Logos kann dein Partner erkennen?": "VW,BMW,Mercedes,Audi,Porsche,Tesla,Toyota,Ford,Honda,Hyundai,Opel,Peugeot,Renault,Fiat,Volvo",
        "Wie viele Programmiersprachen kann dein Partner nennen?": "Python,Java,JavaScript,C++,C#,Swift,Ruby,Go,PHP,TypeScript,Kotlin,Scala,Rust,SQL,HTML",
        "Wie viele Apple-Produkte kann dein Partner aufzählen?": "iPhone,iPad,MacBook,iMac,Apple Watch,AirPods,Apple TV,HomePod,iPod,Mac Mini,Mac Pro,Mac Studio,Magic Mouse,Apple Pencil,AirTag",
        "Wie viele bekannte Videospiel-Konsolen kann dein Partner nennen?": "PlayStation,PS2,PS3,PS4,PS5,Xbox,Xbox 360,Xbox One,Nintendo Switch,Wii,Wii U,GameCube,Nintendo 64,PlayStation Portable,Game Boy",
        "Wie viele Science-Fiction-Filme kann dein Partner aufzählen?": "Star Wars,Star Trek,Matrix,Blade Runner,Interstellar,Inception,Alien,Terminator,Avatar,Dune,Zurück in die Zukunft,Jurassic Park,The Fifth Element,The Martian,Men in Black",
        "Wie viele Planeten im Sonnensystem kann dein Partner in der richtigen Reihenfolge sagen?": "Merkur,Venus,Erde,Mars,Jupiter,Saturn,Uranus,Neptun",
        "Wie viele bekannte Erfinder kann dein Partner nennen?": "Thomas Edison,Nikola Tesla,Alexander Graham Bell,James Watt,Johannes Gutenberg,Leonardo da Vinci,Guglielmo Marconi,Rudolf Diesel,Wright-Brüder,Samuel Morse,Karl Benz,George Stephenson",
        "Wie viele Dinge kann dein Partner nennen, die man NICHT in die Mikrowelle legen sollte?": "Metallbesteck,Alufolie,Styropor,Plastik ohne Mikrowellenzeichen,Eier in Schale,Trauben,Aluschalen,Holzbesteck,Takeaway-Boxen mit Metall,Keramik mit Goldrand,CDs,Schwämme,Alte Gläser,Thermobecher,Backpapier mit Beschichtung",
        "Wie viele Ausreden fürs Zuspätkommen kann dein Partner aufzählen?": "Stau,Bahnverspätung,Wecker nicht gehört,Bus verpasst,Parkplatz gesucht,Umleitung,Technische Probleme,Handy kaputt,Schlüssel vergessen,Kind krank,Meeting länger,Schnee,Unfall,Übelkeit,Haustierproblem",
        "Wie viele Dinge kann dein Partner nennen, die man in einem Hotelzimmer findet?": "Bett,Kopfkissen,Bettdecke,Schreibtisch,Stuhl,TV,Minibar,Safe,Kleiderschrank,Bad,Handtücher,Föhn,Seife,Telefon,Wecker",
        "Wie viele Dinge kann dein Partner nennen, die man auf einer Hochzeit braucht?": "Brautkleid,Anzug,Ringe,Trauredner,Blumenstrauß,Einladungen,Torte,Deko,Musik,Foto/Videograf,Location,Sitzplan,Gästeliste,Sektempfang,Trauzeugen",
        "Wie viele Dinge kann dein Partner nennen, die man am Strand machen kann?": "Sonnenbaden,Schwimmen,Spazieren,Beachvolleyball,Muscheln sammeln,Sandburg bauen,Surfen,Schnorcheln,Picknick,Lesen,Joggen,Ball spielen,Stand-Up-Paddling,Schläfchen,Grillen",
        "Wie viele Dinge kann dein Partner nennen, die man im Winter macht?": "Skifahren,Schlittschuhlaufen,Schneemann bauen,Rodeln,Weihnachtsmarkt besuchen,Plätzchen backen,Glühwein trinken,Schnee schippen,Schneeballschlacht,Winterwandern,Heiße Schokolade trinken,Sauna,Adventskalender öffnen,Kerzen anzünden,Schlittenfahren",
        "Wie viele Dinge kann dein Partner nennen, die man in einem Freizeitpark sieht?": "Achterbahn,Riesenrad,Karussell,Autoscooter,Geisterbahn,Imbissstände,Spielbuden,Toiletten,Parade,Shows,Maskottchen,Wasserbahn,Kinderspielplatz,Schließfächer,Ticketschalter",
        "Wie viele Dinge kann dein Partner nennen, die typisch „deutsch“ sind (Essen, Orte, Sachen)?": "Bratwurst,Sauerkraut,Brezel,Schwarzbrot,Oktoberfest,Biergarten,Autobahn,Schwarzwald,Neuschwanstein,Weihnachtsmarkt,Bundesliga,Dirndl/Lederhose,Kuckucksuhr,Haribo,Stammtisch"
        
        
    ]
}
